/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.idetronic.portlet.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the staff_active service. Represents a row in the &quot;_staff_active&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.idetronic.portlet.model.impl.staff_activeModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.idetronic.portlet.model.impl.staff_activeImpl}.
 * </p>
 *
 * @author Mazlan Mat
 * @see staff_active
 * @see com.idetronic.portlet.model.impl.staff_activeImpl
 * @see com.idetronic.portlet.model.impl.staff_activeModelImpl
 * @generated
 */
public interface staff_activeModel extends BaseModel<staff_active> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a staff_active model instance should use the {@link staff_active} interface instead.
	 */

	/**
	 * Returns the primary key of this staff_active.
	 *
	 * @return the primary key of this staff_active
	 */
	public String getPrimaryKey();

	/**
	 * Sets the primary key of this staff_active.
	 *
	 * @param primaryKey the primary key of this staff_active
	 */
	public void setPrimaryKey(String primaryKey);

	/**
	 * Returns the bp_name of this staff_active.
	 *
	 * @return the bp_name of this staff_active
	 */
	@AutoEscape
	public String getBp_name();

	/**
	 * Sets the bp_name of this staff_active.
	 *
	 * @param bp_name the bp_name of this staff_active
	 */
	public void setBp_name(String bp_name);

	/**
	 * Returns the bp_no_pekerja of this staff_active.
	 *
	 * @return the bp_no_pekerja of this staff_active
	 */
	@AutoEscape
	public String getBp_no_pekerja();

	/**
	 * Sets the bp_no_pekerja of this staff_active.
	 *
	 * @param bp_no_pekerja the bp_no_pekerja of this staff_active
	 */
	public void setBp_no_pekerja(String bp_no_pekerja);

	/**
	 * Returns the bp_no_kp of this staff_active.
	 *
	 * @return the bp_no_kp of this staff_active
	 */
	@AutoEscape
	public String getBp_no_kp();

	/**
	 * Sets the bp_no_kp of this staff_active.
	 *
	 * @param bp_no_kp the bp_no_kp of this staff_active
	 */
	public void setBp_no_kp(String bp_no_kp);

	/**
	 * Returns the bk_jab_hakiki of this staff_active.
	 *
	 * @return the bk_jab_hakiki of this staff_active
	 */
	@AutoEscape
	public String getBk_jab_hakiki();

	/**
	 * Sets the bk_jab_hakiki of this staff_active.
	 *
	 * @param bk_jab_hakiki the bk_jab_hakiki of this staff_active
	 */
	public void setBk_jab_hakiki(String bk_jab_hakiki);

	/**
	 * Returns the bk_jab_hakiki_desc of this staff_active.
	 *
	 * @return the bk_jab_hakiki_desc of this staff_active
	 */
	@AutoEscape
	public String getBk_jab_hakiki_desc();

	/**
	 * Sets the bk_jab_hakiki_desc of this staff_active.
	 *
	 * @param bk_jab_hakiki_desc the bk_jab_hakiki_desc of this staff_active
	 */
	public void setBk_jab_hakiki_desc(String bk_jab_hakiki_desc);

	/**
	 * Returns the bk_jab_sekarang of this staff_active.
	 *
	 * @return the bk_jab_sekarang of this staff_active
	 */
	@AutoEscape
	public String getBk_jab_sekarang();

	/**
	 * Sets the bk_jab_sekarang of this staff_active.
	 *
	 * @param bk_jab_sekarang the bk_jab_sekarang of this staff_active
	 */
	public void setBk_jab_sekarang(String bk_jab_sekarang);

	/**
	 * Returns the bk_jab_sekarang_desc of this staff_active.
	 *
	 * @return the bk_jab_sekarang_desc of this staff_active
	 */
	@AutoEscape
	public String getBk_jab_sekarang_desc();

	/**
	 * Sets the bk_jab_sekarang_desc of this staff_active.
	 *
	 * @param bk_jab_sekarang_desc the bk_jab_sekarang_desc of this staff_active
	 */
	public void setBk_jab_sekarang_desc(String bk_jab_sekarang_desc);

	/**
	 * Returns the bk_jaw_jenis of this staff_active.
	 *
	 * @return the bk_jaw_jenis of this staff_active
	 */
	@AutoEscape
	public String getBk_jaw_jenis();

	/**
	 * Sets the bk_jaw_jenis of this staff_active.
	 *
	 * @param bk_jaw_jenis the bk_jaw_jenis of this staff_active
	 */
	public void setBk_jaw_jenis(String bk_jaw_jenis);

	/**
	 * Returns the al_alamat1 of this staff_active.
	 *
	 * @return the al_alamat1 of this staff_active
	 */
	@AutoEscape
	public String getAl_alamat1();

	/**
	 * Sets the al_alamat1 of this staff_active.
	 *
	 * @param al_alamat1 the al_alamat1 of this staff_active
	 */
	public void setAl_alamat1(String al_alamat1);

	/**
	 * Returns the al_alamat2 of this staff_active.
	 *
	 * @return the al_alamat2 of this staff_active
	 */
	@AutoEscape
	public String getAl_alamat2();

	/**
	 * Sets the al_alamat2 of this staff_active.
	 *
	 * @param al_alamat2 the al_alamat2 of this staff_active
	 */
	public void setAl_alamat2(String al_alamat2);

	/**
	 * Returns the al_alamat3 of this staff_active.
	 *
	 * @return the al_alamat3 of this staff_active
	 */
	@AutoEscape
	public String getAl_alamat3();

	/**
	 * Sets the al_alamat3 of this staff_active.
	 *
	 * @param al_alamat3 the al_alamat3 of this staff_active
	 */
	public void setAl_alamat3(String al_alamat3);

	/**
	 * Returns the al_poskod of this staff_active.
	 *
	 * @return the al_poskod of this staff_active
	 */
	@AutoEscape
	public String getAl_poskod();

	/**
	 * Sets the al_poskod of this staff_active.
	 *
	 * @param al_poskod the al_poskod of this staff_active
	 */
	public void setAl_poskod(String al_poskod);

	/**
	 * Returns the al_bandar of this staff_active.
	 *
	 * @return the al_bandar of this staff_active
	 */
	@AutoEscape
	public String getAl_bandar();

	/**
	 * Sets the al_bandar of this staff_active.
	 *
	 * @param al_bandar the al_bandar of this staff_active
	 */
	public void setAl_bandar(String al_bandar);

	/**
	 * Returns the al_negeri of this staff_active.
	 *
	 * @return the al_negeri of this staff_active
	 */
	@AutoEscape
	public String getAl_negeri();

	/**
	 * Sets the al_negeri of this staff_active.
	 *
	 * @param al_negeri the al_negeri of this staff_active
	 */
	public void setAl_negeri(String al_negeri);

	/**
	 * Returns the al_negara of this staff_active.
	 *
	 * @return the al_negara of this staff_active
	 */
	@AutoEscape
	public String getAl_negara();

	/**
	 * Sets the al_negara of this staff_active.
	 *
	 * @param al_negara the al_negara of this staff_active
	 */
	public void setAl_negara(String al_negara);

	/**
	 * Returns the bp_telefon of this staff_active.
	 *
	 * @return the bp_telefon of this staff_active
	 */
	@AutoEscape
	public String getBp_telefon();

	/**
	 * Sets the bp_telefon of this staff_active.
	 *
	 * @param bp_telefon the bp_telefon of this staff_active
	 */
	public void setBp_telefon(String bp_telefon);

	/**
	 * Returns the bp_email of this staff_active.
	 *
	 * @return the bp_email of this staff_active
	 */
	@AutoEscape
	public String getBp_email();

	/**
	 * Sets the bp_email of this staff_active.
	 *
	 * @param bp_email the bp_email of this staff_active
	 */
	public void setBp_email(String bp_email);

	/**
	 * Returns the bp_tjangka_bsara of this staff_active.
	 *
	 * @return the bp_tjangka_bsara of this staff_active
	 */
	public Date getBp_tjangka_bsara();

	/**
	 * Sets the bp_tjangka_bsara of this staff_active.
	 *
	 * @param bp_tjangka_bsara the bp_tjangka_bsara of this staff_active
	 */
	public void setBp_tjangka_bsara(Date bp_tjangka_bsara);

	/**
	 * Returns the bp_rekod_status of this staff_active.
	 *
	 * @return the bp_rekod_status of this staff_active
	 */
	@AutoEscape
	public String getBp_rekod_status();

	/**
	 * Sets the bp_rekod_status of this staff_active.
	 *
	 * @param bp_rekod_status the bp_rekod_status of this staff_active
	 */
	public void setBp_rekod_status(String bp_rekod_status);

	/**
	 * Returns the bk_jaw_hakiki of this staff_active.
	 *
	 * @return the bk_jaw_hakiki of this staff_active
	 */
	@AutoEscape
	public String getBk_jaw_hakiki();

	/**
	 * Sets the bk_jaw_hakiki of this staff_active.
	 *
	 * @param bk_jaw_hakiki the bk_jaw_hakiki of this staff_active
	 */
	public void setBk_jaw_hakiki(String bk_jaw_hakiki);

	/**
	 * Returns the bk_jaw_hakiki_desc of this staff_active.
	 *
	 * @return the bk_jaw_hakiki_desc of this staff_active
	 */
	@AutoEscape
	public String getBk_jaw_hakiki_desc();

	/**
	 * Sets the bk_jaw_hakiki_desc of this staff_active.
	 *
	 * @param bk_jaw_hakiki_desc the bk_jaw_hakiki_desc of this staff_active
	 */
	public void setBk_jaw_hakiki_desc(String bk_jaw_hakiki_desc);

	/**
	 * Returns the bk_jaw_sekarang of this staff_active.
	 *
	 * @return the bk_jaw_sekarang of this staff_active
	 */
	@AutoEscape
	public String getBk_jaw_sekarang();

	/**
	 * Sets the bk_jaw_sekarang of this staff_active.
	 *
	 * @param bk_jaw_sekarang the bk_jaw_sekarang of this staff_active
	 */
	public void setBk_jaw_sekarang(String bk_jaw_sekarang);

	/**
	 * Returns the bk_jaw_sekarang_desc of this staff_active.
	 *
	 * @return the bk_jaw_sekarang_desc of this staff_active
	 */
	@AutoEscape
	public String getBk_jaw_sekarang_desc();

	/**
	 * Sets the bk_jaw_sekarang_desc of this staff_active.
	 *
	 * @param bk_jaw_sekarang_desc the bk_jaw_sekarang_desc of this staff_active
	 */
	public void setBk_jaw_sekarang_desc(String bk_jaw_sekarang_desc);

	/**
	 * Returns the bk_tarikh_lahir of this staff_active.
	 *
	 * @return the bk_tarikh_lahir of this staff_active
	 */
	public Date getBk_tarikh_lahir();

	/**
	 * Sets the bk_tarikh_lahir of this staff_active.
	 *
	 * @param bk_tarikh_lahir the bk_tarikh_lahir of this staff_active
	 */
	public void setBk_tarikh_lahir(Date bk_tarikh_lahir);

	/**
	 * Returns the bk_tarikh_masuk of this staff_active.
	 *
	 * @return the bk_tarikh_masuk of this staff_active
	 */
	public Date getBk_tarikh_masuk();

	/**
	 * Sets the bk_tarikh_masuk of this staff_active.
	 *
	 * @param bk_tarikh_masuk the bk_tarikh_masuk of this staff_active
	 */
	public void setBk_tarikh_masuk(Date bk_tarikh_masuk);

	/**
	 * Returns the bk_rekod_status of this staff_active.
	 *
	 * @return the bk_rekod_status of this staff_active
	 */
	@AutoEscape
	public String getBk_rekod_status();

	/**
	 * Sets the bk_rekod_status of this staff_active.
	 *
	 * @param bk_rekod_status the bk_rekod_status of this staff_active
	 */
	public void setBk_rekod_status(String bk_rekod_status);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(staff_active staff_active);

	public int hashCode();

	public CacheModel<staff_active> toCacheModel();

	public staff_active toEscapedModel();

	public staff_active toUnescapedModel();

	public String toString();

	public String toXmlString();
}