/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.idetronic.tazkirah.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.GroupedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Tazkirah service. Represents a row in the &quot;tazkirah_Tazkirah&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.idetronic.tazkirah.model.impl.TazkirahModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.idetronic.tazkirah.model.impl.TazkirahImpl}.
 * </p>
 *
 * @author Mazlan Mat
 * @see Tazkirah
 * @see com.idetronic.tazkirah.model.impl.TazkirahImpl
 * @see com.idetronic.tazkirah.model.impl.TazkirahModelImpl
 * @generated
 */
public interface TazkirahModel extends BaseModel<Tazkirah>, GroupedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a tazkirah model instance should use the {@link Tazkirah} interface instead.
	 */

	/**
	 * Returns the primary key of this tazkirah.
	 *
	 * @return the primary key of this tazkirah
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this tazkirah.
	 *
	 * @param primaryKey the primary key of this tazkirah
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the tazkirah ID of this tazkirah.
	 *
	 * @return the tazkirah ID of this tazkirah
	 */
	public long getTazkirahId();

	/**
	 * Sets the tazkirah ID of this tazkirah.
	 *
	 * @param tazkirahId the tazkirah ID of this tazkirah
	 */
	public void setTazkirahId(long tazkirahId);

	/**
	 * Returns the company ID of this tazkirah.
	 *
	 * @return the company ID of this tazkirah
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this tazkirah.
	 *
	 * @param companyId the company ID of this tazkirah
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the group ID of this tazkirah.
	 *
	 * @return the group ID of this tazkirah
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this tazkirah.
	 *
	 * @param groupId the group ID of this tazkirah
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the user ID of this tazkirah.
	 *
	 * @return the user ID of this tazkirah
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this tazkirah.
	 *
	 * @param userId the user ID of this tazkirah
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this tazkirah.
	 *
	 * @return the user uuid of this tazkirah
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this tazkirah.
	 *
	 * @param userUuid the user uuid of this tazkirah
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this tazkirah.
	 *
	 * @return the user name of this tazkirah
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this tazkirah.
	 *
	 * @param userName the user name of this tazkirah
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this tazkirah.
	 *
	 * @return the create date of this tazkirah
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this tazkirah.
	 *
	 * @param createDate the create date of this tazkirah
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this tazkirah.
	 *
	 * @return the modified date of this tazkirah
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this tazkirah.
	 *
	 * @param modifiedDate the modified date of this tazkirah
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the title of this tazkirah.
	 *
	 * @return the title of this tazkirah
	 */
	@AutoEscape
	public String getTitle();

	/**
	 * Sets the title of this tazkirah.
	 *
	 * @param title the title of this tazkirah
	 */
	public void setTitle(String title);

	/**
	 * Returns the content of this tazkirah.
	 *
	 * @return the content of this tazkirah
	 */
	@AutoEscape
	public String getContent();

	/**
	 * Sets the content of this tazkirah.
	 *
	 * @param content the content of this tazkirah
	 */
	public void setContent(String content);

	/**
	 * Returns the category of this tazkirah.
	 *
	 * @return the category of this tazkirah
	 */
	@AutoEscape
	public String getCategory();

	/**
	 * Sets the category of this tazkirah.
	 *
	 * @param category the category of this tazkirah
	 */
	public void setCategory(String category);

	/**
	 * Returns the status of this tazkirah.
	 *
	 * @return the status of this tazkirah
	 */
	public int getStatus();

	/**
	 * Sets the status of this tazkirah.
	 *
	 * @param status the status of this tazkirah
	 */
	public void setStatus(int status);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(Tazkirah tazkirah);

	@Override
	public int hashCode();

	@Override
	public CacheModel<Tazkirah> toCacheModel();

	@Override
	public Tazkirah toEscapedModel();

	@Override
	public Tazkirah toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}