/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.idetronic.portlet.model.impl;

import com.idetronic.portlet.model.staff_active;
import com.idetronic.portlet.model.staff_activeModel;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the staff_active service. Represents a row in the &quot;_staff_active&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.idetronic.portlet.model.staff_activeModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link staff_activeImpl}.
 * </p>
 *
 * @author Mazlan Mat
 * @see staff_activeImpl
 * @see com.idetronic.portlet.model.staff_active
 * @see com.idetronic.portlet.model.staff_activeModel
 * @generated
 */
public class staff_activeModelImpl extends BaseModelImpl<staff_active>
	implements staff_activeModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a staff_active model instance should use the {@link com.idetronic.portlet.model.staff_active} interface instead.
	 */
	public static final String TABLE_NAME = "_staff_active";
	public static final Object[][] TABLE_COLUMNS = {
			{ "bp_name", Types.VARCHAR },
			{ "bp_no_pekerja", Types.VARCHAR },
			{ "bp_no_kp", Types.VARCHAR },
			{ "bk_jab_hakiki", Types.VARCHAR },
			{ "bk_jab_hakiki_desc", Types.VARCHAR },
			{ "bk_jab_sekarang", Types.VARCHAR },
			{ "bk_jab_sekarang_desc", Types.VARCHAR },
			{ "bk_jaw_jenis", Types.VARCHAR },
			{ "al_alamat1", Types.VARCHAR },
			{ "al_alamat2", Types.VARCHAR },
			{ "al_alamat3", Types.VARCHAR },
			{ "al_poskod", Types.VARCHAR },
			{ "al_bandar", Types.VARCHAR },
			{ "al_negeri", Types.VARCHAR },
			{ "al_negara", Types.VARCHAR },
			{ "bp_telefon", Types.VARCHAR },
			{ "bp_email", Types.VARCHAR },
			{ "bp_tjangka_bsara", Types.TIMESTAMP },
			{ "bp_rekod_status", Types.VARCHAR },
			{ "bk_jaw_hakiki", Types.VARCHAR },
			{ "bk_jaw_hakiki_desc", Types.VARCHAR },
			{ "bk_jaw_sekarang", Types.VARCHAR },
			{ "bk_jaw_sekarang_desc", Types.VARCHAR },
			{ "bk_tarikh_lahir", Types.TIMESTAMP },
			{ "bk_tarikh_masuk", Types.TIMESTAMP },
			{ "bk_rekod_status", Types.VARCHAR }
		};
	public static final String TABLE_SQL_CREATE = "create table _staff_active (bp_name VARCHAR(75) null,bp_no_pekerja VARCHAR(75) null,bp_no_kp VARCHAR(75) not null primary key,bk_jab_hakiki VARCHAR(75) null,bk_jab_hakiki_desc VARCHAR(75) null,bk_jab_sekarang VARCHAR(75) null,bk_jab_sekarang_desc VARCHAR(75) null,bk_jaw_jenis VARCHAR(75) null,al_alamat1 VARCHAR(75) null,al_alamat2 VARCHAR(75) null,al_alamat3 VARCHAR(75) null,al_poskod VARCHAR(75) null,al_bandar VARCHAR(75) null,al_negeri VARCHAR(75) null,al_negara VARCHAR(75) null,bp_telefon VARCHAR(75) null,bp_email VARCHAR(75) null,bp_tjangka_bsara DATE null,bp_rekod_status VARCHAR(75) null,bk_jaw_hakiki VARCHAR(75) null,bk_jaw_hakiki_desc VARCHAR(75) null,bk_jaw_sekarang VARCHAR(75) null,bk_jaw_sekarang_desc VARCHAR(75) null,bk_tarikh_lahir DATE null,bk_tarikh_masuk DATE null,bk_rekod_status VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table _staff_active";
	public static final String DATA_SOURCE = "simsDataSource";
	public static final String SESSION_FACTORY = "simsSessionFactory";
	public static final String TX_MANAGER = "simsTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.idetronic.portlet.model.staff_active"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.idetronic.portlet.model.staff_active"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.idetronic.portlet.model.staff_active"));

	public staff_activeModelImpl() {
	}

	public String getPrimaryKey() {
		return _bp_no_kp;
	}

	public void setPrimaryKey(String primaryKey) {
		setBp_no_kp(primaryKey);
	}

	public Serializable getPrimaryKeyObj() {
		return _bp_no_kp;
	}

	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey((String)primaryKeyObj);
	}

	public Class<?> getModelClass() {
		return staff_active.class;
	}

	public String getModelClassName() {
		return staff_active.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("bp_name", getBp_name());
		attributes.put("bp_no_pekerja", getBp_no_pekerja());
		attributes.put("bp_no_kp", getBp_no_kp());
		attributes.put("bk_jab_hakiki", getBk_jab_hakiki());
		attributes.put("bk_jab_hakiki_desc", getBk_jab_hakiki_desc());
		attributes.put("bk_jab_sekarang", getBk_jab_sekarang());
		attributes.put("bk_jab_sekarang_desc", getBk_jab_sekarang_desc());
		attributes.put("bk_jaw_jenis", getBk_jaw_jenis());
		attributes.put("al_alamat1", getAl_alamat1());
		attributes.put("al_alamat2", getAl_alamat2());
		attributes.put("al_alamat3", getAl_alamat3());
		attributes.put("al_poskod", getAl_poskod());
		attributes.put("al_bandar", getAl_bandar());
		attributes.put("al_negeri", getAl_negeri());
		attributes.put("al_negara", getAl_negara());
		attributes.put("bp_telefon", getBp_telefon());
		attributes.put("bp_email", getBp_email());
		attributes.put("bp_tjangka_bsara", getBp_tjangka_bsara());
		attributes.put("bp_rekod_status", getBp_rekod_status());
		attributes.put("bk_jaw_hakiki", getBk_jaw_hakiki());
		attributes.put("bk_jaw_hakiki_desc", getBk_jaw_hakiki_desc());
		attributes.put("bk_jaw_sekarang", getBk_jaw_sekarang());
		attributes.put("bk_jaw_sekarang_desc", getBk_jaw_sekarang_desc());
		attributes.put("bk_tarikh_lahir", getBk_tarikh_lahir());
		attributes.put("bk_tarikh_masuk", getBk_tarikh_masuk());
		attributes.put("bk_rekod_status", getBk_rekod_status());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		String bp_name = (String)attributes.get("bp_name");

		if (bp_name != null) {
			setBp_name(bp_name);
		}

		String bp_no_pekerja = (String)attributes.get("bp_no_pekerja");

		if (bp_no_pekerja != null) {
			setBp_no_pekerja(bp_no_pekerja);
		}

		String bp_no_kp = (String)attributes.get("bp_no_kp");

		if (bp_no_kp != null) {
			setBp_no_kp(bp_no_kp);
		}

		String bk_jab_hakiki = (String)attributes.get("bk_jab_hakiki");

		if (bk_jab_hakiki != null) {
			setBk_jab_hakiki(bk_jab_hakiki);
		}

		String bk_jab_hakiki_desc = (String)attributes.get("bk_jab_hakiki_desc");

		if (bk_jab_hakiki_desc != null) {
			setBk_jab_hakiki_desc(bk_jab_hakiki_desc);
		}

		String bk_jab_sekarang = (String)attributes.get("bk_jab_sekarang");

		if (bk_jab_sekarang != null) {
			setBk_jab_sekarang(bk_jab_sekarang);
		}

		String bk_jab_sekarang_desc = (String)attributes.get(
				"bk_jab_sekarang_desc");

		if (bk_jab_sekarang_desc != null) {
			setBk_jab_sekarang_desc(bk_jab_sekarang_desc);
		}

		String bk_jaw_jenis = (String)attributes.get("bk_jaw_jenis");

		if (bk_jaw_jenis != null) {
			setBk_jaw_jenis(bk_jaw_jenis);
		}

		String al_alamat1 = (String)attributes.get("al_alamat1");

		if (al_alamat1 != null) {
			setAl_alamat1(al_alamat1);
		}

		String al_alamat2 = (String)attributes.get("al_alamat2");

		if (al_alamat2 != null) {
			setAl_alamat2(al_alamat2);
		}

		String al_alamat3 = (String)attributes.get("al_alamat3");

		if (al_alamat3 != null) {
			setAl_alamat3(al_alamat3);
		}

		String al_poskod = (String)attributes.get("al_poskod");

		if (al_poskod != null) {
			setAl_poskod(al_poskod);
		}

		String al_bandar = (String)attributes.get("al_bandar");

		if (al_bandar != null) {
			setAl_bandar(al_bandar);
		}

		String al_negeri = (String)attributes.get("al_negeri");

		if (al_negeri != null) {
			setAl_negeri(al_negeri);
		}

		String al_negara = (String)attributes.get("al_negara");

		if (al_negara != null) {
			setAl_negara(al_negara);
		}

		String bp_telefon = (String)attributes.get("bp_telefon");

		if (bp_telefon != null) {
			setBp_telefon(bp_telefon);
		}

		String bp_email = (String)attributes.get("bp_email");

		if (bp_email != null) {
			setBp_email(bp_email);
		}

		Date bp_tjangka_bsara = (Date)attributes.get("bp_tjangka_bsara");

		if (bp_tjangka_bsara != null) {
			setBp_tjangka_bsara(bp_tjangka_bsara);
		}

		String bp_rekod_status = (String)attributes.get("bp_rekod_status");

		if (bp_rekod_status != null) {
			setBp_rekod_status(bp_rekod_status);
		}

		String bk_jaw_hakiki = (String)attributes.get("bk_jaw_hakiki");

		if (bk_jaw_hakiki != null) {
			setBk_jaw_hakiki(bk_jaw_hakiki);
		}

		String bk_jaw_hakiki_desc = (String)attributes.get("bk_jaw_hakiki_desc");

		if (bk_jaw_hakiki_desc != null) {
			setBk_jaw_hakiki_desc(bk_jaw_hakiki_desc);
		}

		String bk_jaw_sekarang = (String)attributes.get("bk_jaw_sekarang");

		if (bk_jaw_sekarang != null) {
			setBk_jaw_sekarang(bk_jaw_sekarang);
		}

		String bk_jaw_sekarang_desc = (String)attributes.get(
				"bk_jaw_sekarang_desc");

		if (bk_jaw_sekarang_desc != null) {
			setBk_jaw_sekarang_desc(bk_jaw_sekarang_desc);
		}

		Date bk_tarikh_lahir = (Date)attributes.get("bk_tarikh_lahir");

		if (bk_tarikh_lahir != null) {
			setBk_tarikh_lahir(bk_tarikh_lahir);
		}

		Date bk_tarikh_masuk = (Date)attributes.get("bk_tarikh_masuk");

		if (bk_tarikh_masuk != null) {
			setBk_tarikh_masuk(bk_tarikh_masuk);
		}

		String bk_rekod_status = (String)attributes.get("bk_rekod_status");

		if (bk_rekod_status != null) {
			setBk_rekod_status(bk_rekod_status);
		}
	}

	public String getBp_name() {
		if (_bp_name == null) {
			return StringPool.BLANK;
		}
		else {
			return _bp_name;
		}
	}

	public void setBp_name(String bp_name) {
		_bp_name = bp_name;
	}

	public String getBp_no_pekerja() {
		if (_bp_no_pekerja == null) {
			return StringPool.BLANK;
		}
		else {
			return _bp_no_pekerja;
		}
	}

	public void setBp_no_pekerja(String bp_no_pekerja) {
		_bp_no_pekerja = bp_no_pekerja;
	}

	public String getBp_no_kp() {
		if (_bp_no_kp == null) {
			return StringPool.BLANK;
		}
		else {
			return _bp_no_kp;
		}
	}

	public void setBp_no_kp(String bp_no_kp) {
		_bp_no_kp = bp_no_kp;
	}

	public String getBk_jab_hakiki() {
		if (_bk_jab_hakiki == null) {
			return StringPool.BLANK;
		}
		else {
			return _bk_jab_hakiki;
		}
	}

	public void setBk_jab_hakiki(String bk_jab_hakiki) {
		_bk_jab_hakiki = bk_jab_hakiki;
	}

	public String getBk_jab_hakiki_desc() {
		if (_bk_jab_hakiki_desc == null) {
			return StringPool.BLANK;
		}
		else {
			return _bk_jab_hakiki_desc;
		}
	}

	public void setBk_jab_hakiki_desc(String bk_jab_hakiki_desc) {
		_bk_jab_hakiki_desc = bk_jab_hakiki_desc;
	}

	public String getBk_jab_sekarang() {
		if (_bk_jab_sekarang == null) {
			return StringPool.BLANK;
		}
		else {
			return _bk_jab_sekarang;
		}
	}

	public void setBk_jab_sekarang(String bk_jab_sekarang) {
		_bk_jab_sekarang = bk_jab_sekarang;
	}

	public String getBk_jab_sekarang_desc() {
		if (_bk_jab_sekarang_desc == null) {
			return StringPool.BLANK;
		}
		else {
			return _bk_jab_sekarang_desc;
		}
	}

	public void setBk_jab_sekarang_desc(String bk_jab_sekarang_desc) {
		_bk_jab_sekarang_desc = bk_jab_sekarang_desc;
	}

	public String getBk_jaw_jenis() {
		if (_bk_jaw_jenis == null) {
			return StringPool.BLANK;
		}
		else {
			return _bk_jaw_jenis;
		}
	}

	public void setBk_jaw_jenis(String bk_jaw_jenis) {
		_bk_jaw_jenis = bk_jaw_jenis;
	}

	public String getAl_alamat1() {
		if (_al_alamat1 == null) {
			return StringPool.BLANK;
		}
		else {
			return _al_alamat1;
		}
	}

	public void setAl_alamat1(String al_alamat1) {
		_al_alamat1 = al_alamat1;
	}

	public String getAl_alamat2() {
		if (_al_alamat2 == null) {
			return StringPool.BLANK;
		}
		else {
			return _al_alamat2;
		}
	}

	public void setAl_alamat2(String al_alamat2) {
		_al_alamat2 = al_alamat2;
	}

	public String getAl_alamat3() {
		if (_al_alamat3 == null) {
			return StringPool.BLANK;
		}
		else {
			return _al_alamat3;
		}
	}

	public void setAl_alamat3(String al_alamat3) {
		_al_alamat3 = al_alamat3;
	}

	public String getAl_poskod() {
		if (_al_poskod == null) {
			return StringPool.BLANK;
		}
		else {
			return _al_poskod;
		}
	}

	public void setAl_poskod(String al_poskod) {
		_al_poskod = al_poskod;
	}

	public String getAl_bandar() {
		if (_al_bandar == null) {
			return StringPool.BLANK;
		}
		else {
			return _al_bandar;
		}
	}

	public void setAl_bandar(String al_bandar) {
		_al_bandar = al_bandar;
	}

	public String getAl_negeri() {
		if (_al_negeri == null) {
			return StringPool.BLANK;
		}
		else {
			return _al_negeri;
		}
	}

	public void setAl_negeri(String al_negeri) {
		_al_negeri = al_negeri;
	}

	public String getAl_negara() {
		if (_al_negara == null) {
			return StringPool.BLANK;
		}
		else {
			return _al_negara;
		}
	}

	public void setAl_negara(String al_negara) {
		_al_negara = al_negara;
	}

	public String getBp_telefon() {
		if (_bp_telefon == null) {
			return StringPool.BLANK;
		}
		else {
			return _bp_telefon;
		}
	}

	public void setBp_telefon(String bp_telefon) {
		_bp_telefon = bp_telefon;
	}

	public String getBp_email() {
		if (_bp_email == null) {
			return StringPool.BLANK;
		}
		else {
			return _bp_email;
		}
	}

	public void setBp_email(String bp_email) {
		_bp_email = bp_email;
	}

	public Date getBp_tjangka_bsara() {
		return _bp_tjangka_bsara;
	}

	public void setBp_tjangka_bsara(Date bp_tjangka_bsara) {
		_bp_tjangka_bsara = bp_tjangka_bsara;
	}

	public String getBp_rekod_status() {
		if (_bp_rekod_status == null) {
			return StringPool.BLANK;
		}
		else {
			return _bp_rekod_status;
		}
	}

	public void setBp_rekod_status(String bp_rekod_status) {
		_bp_rekod_status = bp_rekod_status;
	}

	public String getBk_jaw_hakiki() {
		if (_bk_jaw_hakiki == null) {
			return StringPool.BLANK;
		}
		else {
			return _bk_jaw_hakiki;
		}
	}

	public void setBk_jaw_hakiki(String bk_jaw_hakiki) {
		_bk_jaw_hakiki = bk_jaw_hakiki;
	}

	public String getBk_jaw_hakiki_desc() {
		if (_bk_jaw_hakiki_desc == null) {
			return StringPool.BLANK;
		}
		else {
			return _bk_jaw_hakiki_desc;
		}
	}

	public void setBk_jaw_hakiki_desc(String bk_jaw_hakiki_desc) {
		_bk_jaw_hakiki_desc = bk_jaw_hakiki_desc;
	}

	public String getBk_jaw_sekarang() {
		if (_bk_jaw_sekarang == null) {
			return StringPool.BLANK;
		}
		else {
			return _bk_jaw_sekarang;
		}
	}

	public void setBk_jaw_sekarang(String bk_jaw_sekarang) {
		_bk_jaw_sekarang = bk_jaw_sekarang;
	}

	public String getBk_jaw_sekarang_desc() {
		if (_bk_jaw_sekarang_desc == null) {
			return StringPool.BLANK;
		}
		else {
			return _bk_jaw_sekarang_desc;
		}
	}

	public void setBk_jaw_sekarang_desc(String bk_jaw_sekarang_desc) {
		_bk_jaw_sekarang_desc = bk_jaw_sekarang_desc;
	}

	public Date getBk_tarikh_lahir() {
		return _bk_tarikh_lahir;
	}

	public void setBk_tarikh_lahir(Date bk_tarikh_lahir) {
		_bk_tarikh_lahir = bk_tarikh_lahir;
	}

	public Date getBk_tarikh_masuk() {
		return _bk_tarikh_masuk;
	}

	public void setBk_tarikh_masuk(Date bk_tarikh_masuk) {
		_bk_tarikh_masuk = bk_tarikh_masuk;
	}

	public String getBk_rekod_status() {
		if (_bk_rekod_status == null) {
			return StringPool.BLANK;
		}
		else {
			return _bk_rekod_status;
		}
	}

	public void setBk_rekod_status(String bk_rekod_status) {
		_bk_rekod_status = bk_rekod_status;
	}

	@Override
	public staff_active toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (staff_active)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	public staff_active toUnescapedModel() {
		return (staff_active)this;
	}

	@Override
	public Object clone() {
		staff_activeImpl staff_activeImpl = new staff_activeImpl();

		staff_activeImpl.setBp_name(getBp_name());
		staff_activeImpl.setBp_no_pekerja(getBp_no_pekerja());
		staff_activeImpl.setBp_no_kp(getBp_no_kp());
		staff_activeImpl.setBk_jab_hakiki(getBk_jab_hakiki());
		staff_activeImpl.setBk_jab_hakiki_desc(getBk_jab_hakiki_desc());
		staff_activeImpl.setBk_jab_sekarang(getBk_jab_sekarang());
		staff_activeImpl.setBk_jab_sekarang_desc(getBk_jab_sekarang_desc());
		staff_activeImpl.setBk_jaw_jenis(getBk_jaw_jenis());
		staff_activeImpl.setAl_alamat1(getAl_alamat1());
		staff_activeImpl.setAl_alamat2(getAl_alamat2());
		staff_activeImpl.setAl_alamat3(getAl_alamat3());
		staff_activeImpl.setAl_poskod(getAl_poskod());
		staff_activeImpl.setAl_bandar(getAl_bandar());
		staff_activeImpl.setAl_negeri(getAl_negeri());
		staff_activeImpl.setAl_negara(getAl_negara());
		staff_activeImpl.setBp_telefon(getBp_telefon());
		staff_activeImpl.setBp_email(getBp_email());
		staff_activeImpl.setBp_tjangka_bsara(getBp_tjangka_bsara());
		staff_activeImpl.setBp_rekod_status(getBp_rekod_status());
		staff_activeImpl.setBk_jaw_hakiki(getBk_jaw_hakiki());
		staff_activeImpl.setBk_jaw_hakiki_desc(getBk_jaw_hakiki_desc());
		staff_activeImpl.setBk_jaw_sekarang(getBk_jaw_sekarang());
		staff_activeImpl.setBk_jaw_sekarang_desc(getBk_jaw_sekarang_desc());
		staff_activeImpl.setBk_tarikh_lahir(getBk_tarikh_lahir());
		staff_activeImpl.setBk_tarikh_masuk(getBk_tarikh_masuk());
		staff_activeImpl.setBk_rekod_status(getBk_rekod_status());

		staff_activeImpl.resetOriginalValues();

		return staff_activeImpl;
	}

	public int compareTo(staff_active staff_active) {
		String primaryKey = staff_active.getPrimaryKey();

		return getPrimaryKey().compareTo(primaryKey);
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof staff_active)) {
			return false;
		}

		staff_active staff_active = (staff_active)obj;

		String primaryKey = staff_active.getPrimaryKey();

		if (getPrimaryKey().equals(primaryKey)) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey().hashCode();
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<staff_active> toCacheModel() {
		staff_activeCacheModel staff_activeCacheModel = new staff_activeCacheModel();

		staff_activeCacheModel.bp_name = getBp_name();

		String bp_name = staff_activeCacheModel.bp_name;

		if ((bp_name != null) && (bp_name.length() == 0)) {
			staff_activeCacheModel.bp_name = null;
		}

		staff_activeCacheModel.bp_no_pekerja = getBp_no_pekerja();

		String bp_no_pekerja = staff_activeCacheModel.bp_no_pekerja;

		if ((bp_no_pekerja != null) && (bp_no_pekerja.length() == 0)) {
			staff_activeCacheModel.bp_no_pekerja = null;
		}

		staff_activeCacheModel.bp_no_kp = getBp_no_kp();

		String bp_no_kp = staff_activeCacheModel.bp_no_kp;

		if ((bp_no_kp != null) && (bp_no_kp.length() == 0)) {
			staff_activeCacheModel.bp_no_kp = null;
		}

		staff_activeCacheModel.bk_jab_hakiki = getBk_jab_hakiki();

		String bk_jab_hakiki = staff_activeCacheModel.bk_jab_hakiki;

		if ((bk_jab_hakiki != null) && (bk_jab_hakiki.length() == 0)) {
			staff_activeCacheModel.bk_jab_hakiki = null;
		}

		staff_activeCacheModel.bk_jab_hakiki_desc = getBk_jab_hakiki_desc();

		String bk_jab_hakiki_desc = staff_activeCacheModel.bk_jab_hakiki_desc;

		if ((bk_jab_hakiki_desc != null) && (bk_jab_hakiki_desc.length() == 0)) {
			staff_activeCacheModel.bk_jab_hakiki_desc = null;
		}

		staff_activeCacheModel.bk_jab_sekarang = getBk_jab_sekarang();

		String bk_jab_sekarang = staff_activeCacheModel.bk_jab_sekarang;

		if ((bk_jab_sekarang != null) && (bk_jab_sekarang.length() == 0)) {
			staff_activeCacheModel.bk_jab_sekarang = null;
		}

		staff_activeCacheModel.bk_jab_sekarang_desc = getBk_jab_sekarang_desc();

		String bk_jab_sekarang_desc = staff_activeCacheModel.bk_jab_sekarang_desc;

		if ((bk_jab_sekarang_desc != null) &&
				(bk_jab_sekarang_desc.length() == 0)) {
			staff_activeCacheModel.bk_jab_sekarang_desc = null;
		}

		staff_activeCacheModel.bk_jaw_jenis = getBk_jaw_jenis();

		String bk_jaw_jenis = staff_activeCacheModel.bk_jaw_jenis;

		if ((bk_jaw_jenis != null) && (bk_jaw_jenis.length() == 0)) {
			staff_activeCacheModel.bk_jaw_jenis = null;
		}

		staff_activeCacheModel.al_alamat1 = getAl_alamat1();

		String al_alamat1 = staff_activeCacheModel.al_alamat1;

		if ((al_alamat1 != null) && (al_alamat1.length() == 0)) {
			staff_activeCacheModel.al_alamat1 = null;
		}

		staff_activeCacheModel.al_alamat2 = getAl_alamat2();

		String al_alamat2 = staff_activeCacheModel.al_alamat2;

		if ((al_alamat2 != null) && (al_alamat2.length() == 0)) {
			staff_activeCacheModel.al_alamat2 = null;
		}

		staff_activeCacheModel.al_alamat3 = getAl_alamat3();

		String al_alamat3 = staff_activeCacheModel.al_alamat3;

		if ((al_alamat3 != null) && (al_alamat3.length() == 0)) {
			staff_activeCacheModel.al_alamat3 = null;
		}

		staff_activeCacheModel.al_poskod = getAl_poskod();

		String al_poskod = staff_activeCacheModel.al_poskod;

		if ((al_poskod != null) && (al_poskod.length() == 0)) {
			staff_activeCacheModel.al_poskod = null;
		}

		staff_activeCacheModel.al_bandar = getAl_bandar();

		String al_bandar = staff_activeCacheModel.al_bandar;

		if ((al_bandar != null) && (al_bandar.length() == 0)) {
			staff_activeCacheModel.al_bandar = null;
		}

		staff_activeCacheModel.al_negeri = getAl_negeri();

		String al_negeri = staff_activeCacheModel.al_negeri;

		if ((al_negeri != null) && (al_negeri.length() == 0)) {
			staff_activeCacheModel.al_negeri = null;
		}

		staff_activeCacheModel.al_negara = getAl_negara();

		String al_negara = staff_activeCacheModel.al_negara;

		if ((al_negara != null) && (al_negara.length() == 0)) {
			staff_activeCacheModel.al_negara = null;
		}

		staff_activeCacheModel.bp_telefon = getBp_telefon();

		String bp_telefon = staff_activeCacheModel.bp_telefon;

		if ((bp_telefon != null) && (bp_telefon.length() == 0)) {
			staff_activeCacheModel.bp_telefon = null;
		}

		staff_activeCacheModel.bp_email = getBp_email();

		String bp_email = staff_activeCacheModel.bp_email;

		if ((bp_email != null) && (bp_email.length() == 0)) {
			staff_activeCacheModel.bp_email = null;
		}

		Date bp_tjangka_bsara = getBp_tjangka_bsara();

		if (bp_tjangka_bsara != null) {
			staff_activeCacheModel.bp_tjangka_bsara = bp_tjangka_bsara.getTime();
		}
		else {
			staff_activeCacheModel.bp_tjangka_bsara = Long.MIN_VALUE;
		}

		staff_activeCacheModel.bp_rekod_status = getBp_rekod_status();

		String bp_rekod_status = staff_activeCacheModel.bp_rekod_status;

		if ((bp_rekod_status != null) && (bp_rekod_status.length() == 0)) {
			staff_activeCacheModel.bp_rekod_status = null;
		}

		staff_activeCacheModel.bk_jaw_hakiki = getBk_jaw_hakiki();

		String bk_jaw_hakiki = staff_activeCacheModel.bk_jaw_hakiki;

		if ((bk_jaw_hakiki != null) && (bk_jaw_hakiki.length() == 0)) {
			staff_activeCacheModel.bk_jaw_hakiki = null;
		}

		staff_activeCacheModel.bk_jaw_hakiki_desc = getBk_jaw_hakiki_desc();

		String bk_jaw_hakiki_desc = staff_activeCacheModel.bk_jaw_hakiki_desc;

		if ((bk_jaw_hakiki_desc != null) && (bk_jaw_hakiki_desc.length() == 0)) {
			staff_activeCacheModel.bk_jaw_hakiki_desc = null;
		}

		staff_activeCacheModel.bk_jaw_sekarang = getBk_jaw_sekarang();

		String bk_jaw_sekarang = staff_activeCacheModel.bk_jaw_sekarang;

		if ((bk_jaw_sekarang != null) && (bk_jaw_sekarang.length() == 0)) {
			staff_activeCacheModel.bk_jaw_sekarang = null;
		}

		staff_activeCacheModel.bk_jaw_sekarang_desc = getBk_jaw_sekarang_desc();

		String bk_jaw_sekarang_desc = staff_activeCacheModel.bk_jaw_sekarang_desc;

		if ((bk_jaw_sekarang_desc != null) &&
				(bk_jaw_sekarang_desc.length() == 0)) {
			staff_activeCacheModel.bk_jaw_sekarang_desc = null;
		}

		Date bk_tarikh_lahir = getBk_tarikh_lahir();

		if (bk_tarikh_lahir != null) {
			staff_activeCacheModel.bk_tarikh_lahir = bk_tarikh_lahir.getTime();
		}
		else {
			staff_activeCacheModel.bk_tarikh_lahir = Long.MIN_VALUE;
		}

		Date bk_tarikh_masuk = getBk_tarikh_masuk();

		if (bk_tarikh_masuk != null) {
			staff_activeCacheModel.bk_tarikh_masuk = bk_tarikh_masuk.getTime();
		}
		else {
			staff_activeCacheModel.bk_tarikh_masuk = Long.MIN_VALUE;
		}

		staff_activeCacheModel.bk_rekod_status = getBk_rekod_status();

		String bk_rekod_status = staff_activeCacheModel.bk_rekod_status;

		if ((bk_rekod_status != null) && (bk_rekod_status.length() == 0)) {
			staff_activeCacheModel.bk_rekod_status = null;
		}

		return staff_activeCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(53);

		sb.append("{bp_name=");
		sb.append(getBp_name());
		sb.append(", bp_no_pekerja=");
		sb.append(getBp_no_pekerja());
		sb.append(", bp_no_kp=");
		sb.append(getBp_no_kp());
		sb.append(", bk_jab_hakiki=");
		sb.append(getBk_jab_hakiki());
		sb.append(", bk_jab_hakiki_desc=");
		sb.append(getBk_jab_hakiki_desc());
		sb.append(", bk_jab_sekarang=");
		sb.append(getBk_jab_sekarang());
		sb.append(", bk_jab_sekarang_desc=");
		sb.append(getBk_jab_sekarang_desc());
		sb.append(", bk_jaw_jenis=");
		sb.append(getBk_jaw_jenis());
		sb.append(", al_alamat1=");
		sb.append(getAl_alamat1());
		sb.append(", al_alamat2=");
		sb.append(getAl_alamat2());
		sb.append(", al_alamat3=");
		sb.append(getAl_alamat3());
		sb.append(", al_poskod=");
		sb.append(getAl_poskod());
		sb.append(", al_bandar=");
		sb.append(getAl_bandar());
		sb.append(", al_negeri=");
		sb.append(getAl_negeri());
		sb.append(", al_negara=");
		sb.append(getAl_negara());
		sb.append(", bp_telefon=");
		sb.append(getBp_telefon());
		sb.append(", bp_email=");
		sb.append(getBp_email());
		sb.append(", bp_tjangka_bsara=");
		sb.append(getBp_tjangka_bsara());
		sb.append(", bp_rekod_status=");
		sb.append(getBp_rekod_status());
		sb.append(", bk_jaw_hakiki=");
		sb.append(getBk_jaw_hakiki());
		sb.append(", bk_jaw_hakiki_desc=");
		sb.append(getBk_jaw_hakiki_desc());
		sb.append(", bk_jaw_sekarang=");
		sb.append(getBk_jaw_sekarang());
		sb.append(", bk_jaw_sekarang_desc=");
		sb.append(getBk_jaw_sekarang_desc());
		sb.append(", bk_tarikh_lahir=");
		sb.append(getBk_tarikh_lahir());
		sb.append(", bk_tarikh_masuk=");
		sb.append(getBk_tarikh_masuk());
		sb.append(", bk_rekod_status=");
		sb.append(getBk_rekod_status());
		sb.append("}");

		return sb.toString();
	}

	public String toXmlString() {
		StringBundler sb = new StringBundler(82);

		sb.append("<model><model-name>");
		sb.append("com.idetronic.portlet.model.staff_active");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>bp_name</column-name><column-value><![CDATA[");
		sb.append(getBp_name());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>bp_no_pekerja</column-name><column-value><![CDATA[");
		sb.append(getBp_no_pekerja());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>bp_no_kp</column-name><column-value><![CDATA[");
		sb.append(getBp_no_kp());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>bk_jab_hakiki</column-name><column-value><![CDATA[");
		sb.append(getBk_jab_hakiki());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>bk_jab_hakiki_desc</column-name><column-value><![CDATA[");
		sb.append(getBk_jab_hakiki_desc());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>bk_jab_sekarang</column-name><column-value><![CDATA[");
		sb.append(getBk_jab_sekarang());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>bk_jab_sekarang_desc</column-name><column-value><![CDATA[");
		sb.append(getBk_jab_sekarang_desc());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>bk_jaw_jenis</column-name><column-value><![CDATA[");
		sb.append(getBk_jaw_jenis());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>al_alamat1</column-name><column-value><![CDATA[");
		sb.append(getAl_alamat1());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>al_alamat2</column-name><column-value><![CDATA[");
		sb.append(getAl_alamat2());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>al_alamat3</column-name><column-value><![CDATA[");
		sb.append(getAl_alamat3());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>al_poskod</column-name><column-value><![CDATA[");
		sb.append(getAl_poskod());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>al_bandar</column-name><column-value><![CDATA[");
		sb.append(getAl_bandar());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>al_negeri</column-name><column-value><![CDATA[");
		sb.append(getAl_negeri());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>al_negara</column-name><column-value><![CDATA[");
		sb.append(getAl_negara());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>bp_telefon</column-name><column-value><![CDATA[");
		sb.append(getBp_telefon());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>bp_email</column-name><column-value><![CDATA[");
		sb.append(getBp_email());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>bp_tjangka_bsara</column-name><column-value><![CDATA[");
		sb.append(getBp_tjangka_bsara());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>bp_rekod_status</column-name><column-value><![CDATA[");
		sb.append(getBp_rekod_status());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>bk_jaw_hakiki</column-name><column-value><![CDATA[");
		sb.append(getBk_jaw_hakiki());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>bk_jaw_hakiki_desc</column-name><column-value><![CDATA[");
		sb.append(getBk_jaw_hakiki_desc());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>bk_jaw_sekarang</column-name><column-value><![CDATA[");
		sb.append(getBk_jaw_sekarang());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>bk_jaw_sekarang_desc</column-name><column-value><![CDATA[");
		sb.append(getBk_jaw_sekarang_desc());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>bk_tarikh_lahir</column-name><column-value><![CDATA[");
		sb.append(getBk_tarikh_lahir());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>bk_tarikh_masuk</column-name><column-value><![CDATA[");
		sb.append(getBk_tarikh_masuk());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>bk_rekod_status</column-name><column-value><![CDATA[");
		sb.append(getBk_rekod_status());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = staff_active.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			staff_active.class
		};
	private String _bp_name;
	private String _bp_no_pekerja;
	private String _bp_no_kp;
	private String _bk_jab_hakiki;
	private String _bk_jab_hakiki_desc;
	private String _bk_jab_sekarang;
	private String _bk_jab_sekarang_desc;
	private String _bk_jaw_jenis;
	private String _al_alamat1;
	private String _al_alamat2;
	private String _al_alamat3;
	private String _al_poskod;
	private String _al_bandar;
	private String _al_negeri;
	private String _al_negara;
	private String _bp_telefon;
	private String _bp_email;
	private Date _bp_tjangka_bsara;
	private String _bp_rekod_status;
	private String _bk_jaw_hakiki;
	private String _bk_jaw_hakiki_desc;
	private String _bk_jaw_sekarang;
	private String _bk_jaw_sekarang_desc;
	private Date _bk_tarikh_lahir;
	private Date _bk_tarikh_masuk;
	private String _bk_rekod_status;
	private staff_active _escapedModel;
}