/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.idetronic.subur.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the AuthorSite service. Represents a row in the &quot;Subur_AuthorSite&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.idetronic.subur.model.impl.AuthorSiteModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.idetronic.subur.model.impl.AuthorSiteImpl}.
 * </p>
 *
 * @author Mazlan Mat
 * @see AuthorSite
 * @see com.idetronic.subur.model.impl.AuthorSiteImpl
 * @see com.idetronic.subur.model.impl.AuthorSiteModelImpl
 * @generated
 */
public interface AuthorSiteModel extends BaseModel<AuthorSite> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a author site model instance should use the {@link AuthorSite} interface instead.
	 */

	/**
	 * Returns the primary key of this author site.
	 *
	 * @return the primary key of this author site
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this author site.
	 *
	 * @param primaryKey the primary key of this author site
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the author site ID of this author site.
	 *
	 * @return the author site ID of this author site
	 */
	public long getAuthorSiteId();

	/**
	 * Sets the author site ID of this author site.
	 *
	 * @param authorSiteId the author site ID of this author site
	 */
	public void setAuthorSiteId(long authorSiteId);

	/**
	 * Returns the author ID of this author site.
	 *
	 * @return the author ID of this author site
	 */
	public long getAuthorId();

	/**
	 * Sets the author ID of this author site.
	 *
	 * @param authorId the author ID of this author site
	 */
	public void setAuthorId(long authorId);

	/**
	 * Returns the site name of this author site.
	 *
	 * @return the site name of this author site
	 */
	@AutoEscape
	public String getSiteName();

	/**
	 * Sets the site name of this author site.
	 *
	 * @param siteName the site name of this author site
	 */
	public void setSiteName(String siteName);

	/**
	 * Returns the site u r l of this author site.
	 *
	 * @return the site u r l of this author site
	 */
	@AutoEscape
	public String getSiteURL();

	/**
	 * Sets the site u r l of this author site.
	 *
	 * @param siteURL the site u r l of this author site
	 */
	public void setSiteURL(String siteURL);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.idetronic.subur.model.AuthorSite authorSite);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.idetronic.subur.model.AuthorSite> toCacheModel();

	@Override
	public com.idetronic.subur.model.AuthorSite toEscapedModel();

	@Override
	public com.idetronic.subur.model.AuthorSite toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}