/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.idetronic.subur.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Author service. Represents a row in the &quot;subur_Author&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.idetronic.subur.model.impl.AuthorModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.idetronic.subur.model.impl.AuthorImpl}.
 * </p>
 *
 * @author Mazlan Mat
 * @see Author
 * @see com.idetronic.subur.model.impl.AuthorImpl
 * @see com.idetronic.subur.model.impl.AuthorModelImpl
 * @generated
 */
public interface AuthorModel extends BaseModel<Author> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a author model instance should use the {@link Author} interface instead.
	 */

	/**
	 * Returns the primary key of this author.
	 *
	 * @return the primary key of this author
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this author.
	 *
	 * @param primaryKey the primary key of this author
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the author ID of this author.
	 *
	 * @return the author ID of this author
	 */
	public long getAuthorId();

	/**
	 * Sets the author ID of this author.
	 *
	 * @param authorId the author ID of this author
	 */
	public void setAuthorId(long authorId);

	/**
	 * Returns the group ID of this author.
	 *
	 * @return the group ID of this author
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this author.
	 *
	 * @param groupId the group ID of this author
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this author.
	 *
	 * @return the company ID of this author
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this author.
	 *
	 * @param companyId the company ID of this author
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the title of this author.
	 *
	 * @return the title of this author
	 */
	@AutoEscape
	public String getTitle();

	/**
	 * Sets the title of this author.
	 *
	 * @param title the title of this author
	 */
	public void setTitle(String title);

	/**
	 * Returns the id type of this author.
	 *
	 * @return the id type of this author
	 */
	public int getIdType();

	/**
	 * Sets the id type of this author.
	 *
	 * @param idType the id type of this author
	 */
	public void setIdType(int idType);

	/**
	 * Returns the remote ID of this author.
	 *
	 * @return the remote ID of this author
	 */
	@AutoEscape
	public String getRemoteId();

	/**
	 * Sets the remote ID of this author.
	 *
	 * @param remoteId the remote ID of this author
	 */
	public void setRemoteId(String remoteId);

	/**
	 * Returns the first name of this author.
	 *
	 * @return the first name of this author
	 */
	@AutoEscape
	public String getFirstName();

	/**
	 * Sets the first name of this author.
	 *
	 * @param firstName the first name of this author
	 */
	public void setFirstName(String firstName);

	/**
	 * Returns the last name of this author.
	 *
	 * @return the last name of this author
	 */
	@AutoEscape
	public String getLastName();

	/**
	 * Sets the last name of this author.
	 *
	 * @param lastName the last name of this author
	 */
	public void setLastName(String lastName);

	/**
	 * Returns the user ID of this author.
	 *
	 * @return the user ID of this author
	 */
	public int getUserId();

	/**
	 * Sets the user ID of this author.
	 *
	 * @param userId the user ID of this author
	 */
	public void setUserId(int userId);

	/**
	 * Returns the metadata of this author.
	 *
	 * @return the metadata of this author
	 */
	@AutoEscape
	public String getMetadata();

	/**
	 * Sets the metadata of this author.
	 *
	 * @param metadata the metadata of this author
	 */
	public void setMetadata(String metadata);

	/**
	 * Returns the last published date of this author.
	 *
	 * @return the last published date of this author
	 */
	public Date getLastPublishedDate();

	/**
	 * Sets the last published date of this author.
	 *
	 * @param lastPublishedDate the last published date of this author
	 */
	public void setLastPublishedDate(Date lastPublishedDate);

	/**
	 * Returns the item count of this author.
	 *
	 * @return the item count of this author
	 */
	public int getItemCount();

	/**
	 * Sets the item count of this author.
	 *
	 * @param itemCount the item count of this author
	 */
	public void setItemCount(int itemCount);

	/**
	 * Returns the personal site of this author.
	 *
	 * @return the personal site of this author
	 */
	@AutoEscape
	public String getPersonalSite();

	/**
	 * Sets the personal site of this author.
	 *
	 * @param personalSite the personal site of this author
	 */
	public void setPersonalSite(String personalSite);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.idetronic.subur.model.Author author);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.idetronic.subur.model.Author> toCacheModel();

	@Override
	public com.idetronic.subur.model.Author toEscapedModel();

	@Override
	public com.idetronic.subur.model.Author toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}