/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.idetronic.subur.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the Division service. Represents a row in the &quot;subur_Division&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.idetronic.subur.model.impl.DivisionModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.idetronic.subur.model.impl.DivisionImpl}.
 * </p>
 *
 * @author Mazlan Mat
 * @see Division
 * @see com.idetronic.subur.model.impl.DivisionImpl
 * @see com.idetronic.subur.model.impl.DivisionModelImpl
 * @generated
 */
public interface DivisionModel extends BaseModel<Division> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a division model instance should use the {@link Division} interface instead.
	 */

	/**
	 * Returns the primary key of this division.
	 *
	 * @return the primary key of this division
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this division.
	 *
	 * @param primaryKey the primary key of this division
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the division ID of this division.
	 *
	 * @return the division ID of this division
	 */
	public long getDivisionId();

	/**
	 * Sets the division ID of this division.
	 *
	 * @param divisionId the division ID of this division
	 */
	public void setDivisionId(long divisionId);

	/**
	 * Returns the parent ID of this division.
	 *
	 * @return the parent ID of this division
	 */
	public long getParentId();

	/**
	 * Sets the parent ID of this division.
	 *
	 * @param parentId the parent ID of this division
	 */
	public void setParentId(long parentId);

	/**
	 * Returns the division name of this division.
	 *
	 * @return the division name of this division
	 */
	@AutoEscape
	public String getDivisionName();

	/**
	 * Sets the division name of this division.
	 *
	 * @param divisionName the division name of this division
	 */
	public void setDivisionName(String divisionName);

	/**
	 * Returns the depositable of this division.
	 *
	 * @return the depositable of this division
	 */
	public boolean getDepositable();

	/**
	 * Returns <code>true</code> if this division is depositable.
	 *
	 * @return <code>true</code> if this division is depositable; <code>false</code> otherwise
	 */
	public boolean isDepositable();

	/**
	 * Sets whether this division is depositable.
	 *
	 * @param depositable the depositable of this division
	 */
	public void setDepositable(boolean depositable);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.idetronic.subur.model.Division division);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.idetronic.subur.model.Division> toCacheModel();

	@Override
	public com.idetronic.subur.model.Division toEscapedModel();

	@Override
	public com.idetronic.subur.model.Division toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}