/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.idetronic.subur.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the FileEntryType service. Represents a row in the &quot;subur_FileEntryType&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.idetronic.subur.model.impl.FileEntryTypeModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.idetronic.subur.model.impl.FileEntryTypeImpl}.
 * </p>
 *
 * @author Mazlan Mat
 * @see FileEntryType
 * @see com.idetronic.subur.model.impl.FileEntryTypeImpl
 * @see com.idetronic.subur.model.impl.FileEntryTypeModelImpl
 * @generated
 */
public interface FileEntryTypeModel extends BaseModel<FileEntryType> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a file entry type model instance should use the {@link FileEntryType} interface instead.
	 */

	/**
	 * Returns the primary key of this file entry type.
	 *
	 * @return the primary key of this file entry type
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this file entry type.
	 *
	 * @param primaryKey the primary key of this file entry type
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the type ID of this file entry type.
	 *
	 * @return the type ID of this file entry type
	 */
	public long getTypeId();

	/**
	 * Sets the type ID of this file entry type.
	 *
	 * @param typeId the type ID of this file entry type
	 */
	public void setTypeId(long typeId);

	/**
	 * Returns the type name of this file entry type.
	 *
	 * @return the type name of this file entry type
	 */
	@AutoEscape
	public String getTypeName();

	/**
	 * Sets the type name of this file entry type.
	 *
	 * @param typeName the type name of this file entry type
	 */
	public void setTypeName(String typeName);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.idetronic.subur.model.FileEntryType fileEntryType);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.idetronic.subur.model.FileEntryType> toCacheModel();

	@Override
	public com.idetronic.subur.model.FileEntryType toEscapedModel();

	@Override
	public com.idetronic.subur.model.FileEntryType toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}