/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.idetronic.subur.model;

import com.idetronic.subur.service.persistence.ItemFileEntryPK;

import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the ItemFileEntry service. Represents a row in the &quot;subur_ItemFileEntry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.idetronic.subur.model.impl.ItemFileEntryModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.idetronic.subur.model.impl.ItemFileEntryImpl}.
 * </p>
 *
 * @author Mazlan Mat
 * @see ItemFileEntry
 * @see com.idetronic.subur.model.impl.ItemFileEntryImpl
 * @see com.idetronic.subur.model.impl.ItemFileEntryModelImpl
 * @generated
 */
public interface ItemFileEntryModel extends BaseModel<ItemFileEntry> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a item file entry model instance should use the {@link ItemFileEntry} interface instead.
	 */

	/**
	 * Returns the primary key of this item file entry.
	 *
	 * @return the primary key of this item file entry
	 */
	public ItemFileEntryPK getPrimaryKey();

	/**
	 * Sets the primary key of this item file entry.
	 *
	 * @param primaryKey the primary key of this item file entry
	 */
	public void setPrimaryKey(ItemFileEntryPK primaryKey);

	/**
	 * Returns the item ID of this item file entry.
	 *
	 * @return the item ID of this item file entry
	 */
	public long getItemId();

	/**
	 * Sets the item ID of this item file entry.
	 *
	 * @param itemId the item ID of this item file entry
	 */
	public void setItemId(long itemId);

	/**
	 * Returns the file entry ID of this item file entry.
	 *
	 * @return the file entry ID of this item file entry
	 */
	public long getFileEntryId();

	/**
	 * Sets the file entry ID of this item file entry.
	 *
	 * @param fileEntryId the file entry ID of this item file entry
	 */
	public void setFileEntryId(long fileEntryId);

	/**
	 * Returns the entry type of this item file entry.
	 *
	 * @return the entry type of this item file entry
	 */
	public long getEntryType();

	/**
	 * Sets the entry type of this item file entry.
	 *
	 * @param entryType the entry type of this item file entry
	 */
	public void setEntryType(long entryType);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.idetronic.subur.model.ItemFileEntry itemFileEntry);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.idetronic.subur.model.ItemFileEntry> toCacheModel();

	@Override
	public com.idetronic.subur.model.ItemFileEntry toEscapedModel();

	@Override
	public com.idetronic.subur.model.ItemFileEntry toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}