/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.idetronic.subur.model;

import com.idetronic.subur.service.persistence.ItemItemTypePK;

import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the ItemItemType service. Represents a row in the &quot;Subur_ItemItemType&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.idetronic.subur.model.impl.ItemItemTypeModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.idetronic.subur.model.impl.ItemItemTypeImpl}.
 * </p>
 *
 * @author Mazlan Mat
 * @see ItemItemType
 * @see com.idetronic.subur.model.impl.ItemItemTypeImpl
 * @see com.idetronic.subur.model.impl.ItemItemTypeModelImpl
 * @generated
 */
public interface ItemItemTypeModel extends BaseModel<ItemItemType> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a item item type model instance should use the {@link ItemItemType} interface instead.
	 */

	/**
	 * Returns the primary key of this item item type.
	 *
	 * @return the primary key of this item item type
	 */
	public ItemItemTypePK getPrimaryKey();

	/**
	 * Sets the primary key of this item item type.
	 *
	 * @param primaryKey the primary key of this item item type
	 */
	public void setPrimaryKey(ItemItemTypePK primaryKey);

	/**
	 * Returns the item ID of this item item type.
	 *
	 * @return the item ID of this item item type
	 */
	public long getItemId();

	/**
	 * Sets the item ID of this item item type.
	 *
	 * @param itemId the item ID of this item item type
	 */
	public void setItemId(long itemId);

	/**
	 * Returns the item type ID of this item item type.
	 *
	 * @return the item type ID of this item item type
	 */
	public long getItemTypeId();

	/**
	 * Sets the item type ID of this item item type.
	 *
	 * @param itemTypeId the item type ID of this item item type
	 */
	public void setItemTypeId(long itemTypeId);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.idetronic.subur.model.ItemItemType itemItemType);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.idetronic.subur.model.ItemItemType> toCacheModel();

	@Override
	public com.idetronic.subur.model.ItemItemType toEscapedModel();

	@Override
	public com.idetronic.subur.model.ItemItemType toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}