/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.idetronic.subur.model;

import com.idetronic.subur.service.persistence.ItemSubjectPK;

import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the ItemSubject service. Represents a row in the &quot;subur_ItemSubject&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.idetronic.subur.model.impl.ItemSubjectModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.idetronic.subur.model.impl.ItemSubjectImpl}.
 * </p>
 *
 * @author Mazlan Mat
 * @see ItemSubject
 * @see com.idetronic.subur.model.impl.ItemSubjectImpl
 * @see com.idetronic.subur.model.impl.ItemSubjectModelImpl
 * @generated
 */
public interface ItemSubjectModel extends BaseModel<ItemSubject> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a item subject model instance should use the {@link ItemSubject} interface instead.
	 */

	/**
	 * Returns the primary key of this item subject.
	 *
	 * @return the primary key of this item subject
	 */
	public ItemSubjectPK getPrimaryKey();

	/**
	 * Sets the primary key of this item subject.
	 *
	 * @param primaryKey the primary key of this item subject
	 */
	public void setPrimaryKey(ItemSubjectPK primaryKey);

	/**
	 * Returns the item ID of this item subject.
	 *
	 * @return the item ID of this item subject
	 */
	public long getItemId();

	/**
	 * Sets the item ID of this item subject.
	 *
	 * @param itemId the item ID of this item subject
	 */
	public void setItemId(long itemId);

	/**
	 * Returns the subject ID of this item subject.
	 *
	 * @return the subject ID of this item subject
	 */
	public long getSubjectId();

	/**
	 * Sets the subject ID of this item subject.
	 *
	 * @param subjectId the subject ID of this item subject
	 */
	public void setSubjectId(long subjectId);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.idetronic.subur.model.ItemSubject itemSubject);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.idetronic.subur.model.ItemSubject> toCacheModel();

	@Override
	public com.idetronic.subur.model.ItemSubject toEscapedModel();

	@Override
	public com.idetronic.subur.model.ItemSubject toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}