/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.idetronic.subur.model;

import com.idetronic.subur.service.persistence.ItemDivisionPK;

import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the ItemDivision service. Represents a row in the &quot;subur_ItemDivision&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.idetronic.subur.model.impl.ItemDivisionModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.idetronic.subur.model.impl.ItemDivisionImpl}.
 * </p>
 *
 * @author Mazlan Mat
 * @see ItemDivision
 * @see com.idetronic.subur.model.impl.ItemDivisionImpl
 * @see com.idetronic.subur.model.impl.ItemDivisionModelImpl
 * @generated
 */
public interface ItemDivisionModel extends BaseModel<ItemDivision> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a item division model instance should use the {@link ItemDivision} interface instead.
	 */

	/**
	 * Returns the primary key of this item division.
	 *
	 * @return the primary key of this item division
	 */
	public ItemDivisionPK getPrimaryKey();

	/**
	 * Sets the primary key of this item division.
	 *
	 * @param primaryKey the primary key of this item division
	 */
	public void setPrimaryKey(ItemDivisionPK primaryKey);

	/**
	 * Returns the item ID of this item division.
	 *
	 * @return the item ID of this item division
	 */
	public long getItemId();

	/**
	 * Sets the item ID of this item division.
	 *
	 * @param itemId the item ID of this item division
	 */
	public void setItemId(long itemId);

	/**
	 * Returns the division ID of this item division.
	 *
	 * @return the division ID of this item division
	 */
	public long getDivisionId();

	/**
	 * Sets the division ID of this item division.
	 *
	 * @param divisionId the division ID of this item division
	 */
	public void setDivisionId(long divisionId);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.idetronic.subur.model.ItemDivision itemDivision);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.idetronic.subur.model.ItemDivision> toCacheModel();

	@Override
	public com.idetronic.subur.model.ItemDivision toEscapedModel();

	@Override
	public com.idetronic.subur.model.ItemDivision toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}