/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.idetronic.subur.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the MetadataSchema service. Represents a row in the &quot;subur_MetadataSchema&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.idetronic.subur.model.impl.MetadataSchemaModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.idetronic.subur.model.impl.MetadataSchemaImpl}.
 * </p>
 *
 * @author Mazlan Mat
 * @see MetadataSchema
 * @see com.idetronic.subur.model.impl.MetadataSchemaImpl
 * @see com.idetronic.subur.model.impl.MetadataSchemaModelImpl
 * @generated
 */
public interface MetadataSchemaModel extends BaseModel<MetadataSchema> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a metadata schema model instance should use the {@link MetadataSchema} interface instead.
	 */

	/**
	 * Returns the primary key of this metadata schema.
	 *
	 * @return the primary key of this metadata schema
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this metadata schema.
	 *
	 * @param primaryKey the primary key of this metadata schema
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the metadata schema ID of this metadata schema.
	 *
	 * @return the metadata schema ID of this metadata schema
	 */
	public long getMetadataSchemaId();

	/**
	 * Sets the metadata schema ID of this metadata schema.
	 *
	 * @param metadataSchemaId the metadata schema ID of this metadata schema
	 */
	public void setMetadataSchemaId(long metadataSchemaId);

	/**
	 * Returns the metadata name of this metadata schema.
	 *
	 * @return the metadata name of this metadata schema
	 */
	@AutoEscape
	public String getMetadataName();

	/**
	 * Sets the metadata name of this metadata schema.
	 *
	 * @param metadataName the metadata name of this metadata schema
	 */
	public void setMetadataName(String metadataName);

	/**
	 * Returns the name space of this metadata schema.
	 *
	 * @return the name space of this metadata schema
	 */
	@AutoEscape
	public String getNameSpace();

	/**
	 * Sets the name space of this metadata schema.
	 *
	 * @param nameSpace the name space of this metadata schema
	 */
	public void setNameSpace(String nameSpace);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		com.idetronic.subur.model.MetadataSchema metadataSchema);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.idetronic.subur.model.MetadataSchema> toCacheModel();

	@Override
	public com.idetronic.subur.model.MetadataSchema toEscapedModel();

	@Override
	public com.idetronic.subur.model.MetadataSchema toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}