/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.idetronic.subur.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the MetadataPropertyValue service. Represents a row in the &quot;Subur_MetadataPropertyValue&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.idetronic.subur.model.impl.MetadataPropertyValueModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.idetronic.subur.model.impl.MetadataPropertyValueImpl}.
 * </p>
 *
 * @author Mazlan Mat
 * @see MetadataPropertyValue
 * @see com.idetronic.subur.model.impl.MetadataPropertyValueImpl
 * @see com.idetronic.subur.model.impl.MetadataPropertyValueModelImpl
 * @generated
 */
public interface MetadataPropertyValueModel extends BaseModel<MetadataPropertyValue> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a metadata property value model instance should use the {@link MetadataPropertyValue} interface instead.
	 */

	/**
	 * Returns the primary key of this metadata property value.
	 *
	 * @return the primary key of this metadata property value
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this metadata property value.
	 *
	 * @param primaryKey the primary key of this metadata property value
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the metadata property value ID of this metadata property value.
	 *
	 * @return the metadata property value ID of this metadata property value
	 */
	public long getMetadataPropertyValueId();

	/**
	 * Sets the metadata property value ID of this metadata property value.
	 *
	 * @param metadataPropertyValueId the metadata property value ID of this metadata property value
	 */
	public void setMetadataPropertyValueId(long metadataPropertyValueId);

	/**
	 * Returns the item ID of this metadata property value.
	 *
	 * @return the item ID of this metadata property value
	 */
	public long getItemId();

	/**
	 * Sets the item ID of this metadata property value.
	 *
	 * @param itemId the item ID of this metadata property value
	 */
	public void setItemId(long itemId);

	/**
	 * Returns the property ID of this metadata property value.
	 *
	 * @return the property ID of this metadata property value
	 */
	public long getPropertyId();

	/**
	 * Sets the property ID of this metadata property value.
	 *
	 * @param propertyId the property ID of this metadata property value
	 */
	public void setPropertyId(long propertyId);

	/**
	 * Returns the text value of this metadata property value.
	 *
	 * @return the text value of this metadata property value
	 */
	@AutoEscape
	public String getTextValue();

	/**
	 * Sets the text value of this metadata property value.
	 *
	 * @param textValue the text value of this metadata property value
	 */
	public void setTextValue(String textValue);

	/**
	 * Returns the item count of this metadata property value.
	 *
	 * @return the item count of this metadata property value
	 */
	public int getItemCount();

	/**
	 * Sets the item count of this metadata property value.
	 *
	 * @param itemCount the item count of this metadata property value
	 */
	public void setItemCount(int itemCount);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		com.idetronic.subur.model.MetadataPropertyValue metadataPropertyValue);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.idetronic.subur.model.MetadataPropertyValue> toCacheModel();

	@Override
	public com.idetronic.subur.model.MetadataPropertyValue toEscapedModel();

	@Override
	public com.idetronic.subur.model.MetadataPropertyValue toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}