/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.idetronic.subur.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the MetadataValue service. Represents a row in the &quot;subur_MetadataValue&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.idetronic.subur.model.impl.MetadataValueModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.idetronic.subur.model.impl.MetadataValueImpl}.
 * </p>
 *
 * @author Mazlan Mat
 * @see MetadataValue
 * @see com.idetronic.subur.model.impl.MetadataValueImpl
 * @see com.idetronic.subur.model.impl.MetadataValueModelImpl
 * @generated
 */
public interface MetadataValueModel extends BaseModel<MetadataValue> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a metadata value model instance should use the {@link MetadataValue} interface instead.
	 */

	/**
	 * Returns the primary key of this metadata value.
	 *
	 * @return the primary key of this metadata value
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this metadata value.
	 *
	 * @param primaryKey the primary key of this metadata value
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the metadata value ID of this metadata value.
	 *
	 * @return the metadata value ID of this metadata value
	 */
	public long getMetadataValueId();

	/**
	 * Sets the metadata value ID of this metadata value.
	 *
	 * @param metadataValueId the metadata value ID of this metadata value
	 */
	public void setMetadataValueId(long metadataValueId);

	/**
	 * Returns the item ID of this metadata value.
	 *
	 * @return the item ID of this metadata value
	 */
	public long getItemId();

	/**
	 * Sets the item ID of this metadata value.
	 *
	 * @param itemId the item ID of this metadata value
	 */
	public void setItemId(long itemId);

	/**
	 * Returns the property ID of this metadata value.
	 *
	 * @return the property ID of this metadata value
	 */
	public long getPropertyId();

	/**
	 * Sets the property ID of this metadata value.
	 *
	 * @param propertyId the property ID of this metadata value
	 */
	public void setPropertyId(long propertyId);

	/**
	 * Returns the text value of this metadata value.
	 *
	 * @return the text value of this metadata value
	 */
	@AutoEscape
	public String getTextValue();

	/**
	 * Sets the text value of this metadata value.
	 *
	 * @param textValue the text value of this metadata value
	 */
	public void setTextValue(String textValue);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(MetadataValue metadataValue);

	@Override
	public int hashCode();

	@Override
	public CacheModel<MetadataValue> toCacheModel();

	@Override
	public MetadataValue toEscapedModel();

	@Override
	public MetadataValue toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}