/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.idetronic.eprint.service.base;

import com.idetronic.eprint.model.EprintSubject;
import com.idetronic.eprint.service.EprintSubjectLocalService;
import com.idetronic.eprint.service.persistence.EprintDivisionPersistence;
import com.idetronic.eprint.service.persistence.EprintFinder;
import com.idetronic.eprint.service.persistence.EprintPersistence;
import com.idetronic.eprint.service.persistence.EprintStaticContentPersistence;
import com.idetronic.eprint.service.persistence.EprintSubjectPK;
import com.idetronic.eprint.service.persistence.EprintSubjectPersistence;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.bean.IdentifiableBean;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.model.PersistedModel;
import com.liferay.portal.service.BaseLocalServiceImpl;
import com.liferay.portal.service.PersistedModelLocalServiceRegistryUtil;
import com.liferay.portal.service.persistence.UserPersistence;

import java.io.Serializable;

import java.util.List;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the eprint subject local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.idetronic.eprint.service.impl.EprintSubjectLocalServiceImpl}.
 * </p>
 *
 * @author Mazlan Mat
 * @see com.idetronic.eprint.service.impl.EprintSubjectLocalServiceImpl
 * @see com.idetronic.eprint.service.EprintSubjectLocalServiceUtil
 * @generated
 */
public abstract class EprintSubjectLocalServiceBaseImpl
	extends BaseLocalServiceImpl implements EprintSubjectLocalService,
		IdentifiableBean {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Always use {@link com.idetronic.eprint.service.EprintSubjectLocalServiceUtil} to access the eprint subject local service.
	 */

	/**
	 * Adds the eprint subject to the database. Also notifies the appropriate model listeners.
	 *
	 * @param eprintSubject the eprint subject
	 * @return the eprint subject that was added
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public EprintSubject addEprintSubject(EprintSubject eprintSubject)
		throws SystemException {
		eprintSubject.setNew(true);

		return eprintSubjectPersistence.update(eprintSubject);
	}

	/**
	 * Creates a new eprint subject with the primary key. Does not add the eprint subject to the database.
	 *
	 * @param eprintSubjectPK the primary key for the new eprint subject
	 * @return the new eprint subject
	 */
	@Override
	public EprintSubject createEprintSubject(EprintSubjectPK eprintSubjectPK) {
		return eprintSubjectPersistence.create(eprintSubjectPK);
	}

	/**
	 * Deletes the eprint subject with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * @param eprintSubjectPK the primary key of the eprint subject
	 * @return the eprint subject that was removed
	 * @throws PortalException if a eprint subject with the primary key could not be found
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public EprintSubject deleteEprintSubject(EprintSubjectPK eprintSubjectPK)
		throws PortalException, SystemException {
		return eprintSubjectPersistence.remove(eprintSubjectPK);
	}

	/**
	 * Deletes the eprint subject from the database. Also notifies the appropriate model listeners.
	 *
	 * @param eprintSubject the eprint subject
	 * @return the eprint subject that was removed
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public EprintSubject deleteEprintSubject(EprintSubject eprintSubject)
		throws SystemException {
		return eprintSubjectPersistence.remove(eprintSubject);
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(EprintSubject.class,
			clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery)
		throws SystemException {
		return eprintSubjectPersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link com.idetronic.eprint.model.impl.EprintSubjectModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery, int start, int end)
		throws SystemException {
		return eprintSubjectPersistence.findWithDynamicQuery(dynamicQuery,
			start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link com.idetronic.eprint.model.impl.EprintSubjectModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator orderByComparator) throws SystemException {
		return eprintSubjectPersistence.findWithDynamicQuery(dynamicQuery,
			start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows that match the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows that match the dynamic query
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery)
		throws SystemException {
		return eprintSubjectPersistence.countWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Returns the number of rows that match the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows that match the dynamic query
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery,
		Projection projection) throws SystemException {
		return eprintSubjectPersistence.countWithDynamicQuery(dynamicQuery,
			projection);
	}

	@Override
	public EprintSubject fetchEprintSubject(EprintSubjectPK eprintSubjectPK)
		throws SystemException {
		return eprintSubjectPersistence.fetchByPrimaryKey(eprintSubjectPK);
	}

	/**
	 * Returns the eprint subject with the primary key.
	 *
	 * @param eprintSubjectPK the primary key of the eprint subject
	 * @return the eprint subject
	 * @throws PortalException if a eprint subject with the primary key could not be found
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public EprintSubject getEprintSubject(EprintSubjectPK eprintSubjectPK)
		throws PortalException, SystemException {
		return eprintSubjectPersistence.findByPrimaryKey(eprintSubjectPK);
	}

	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException, SystemException {
		return eprintSubjectPersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns a range of all the eprint subjects.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link com.idetronic.eprint.model.impl.EprintSubjectModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param start the lower bound of the range of eprint subjects
	 * @param end the upper bound of the range of eprint subjects (not inclusive)
	 * @return the range of eprint subjects
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public List<EprintSubject> getEprintSubjects(int start, int end)
		throws SystemException {
		return eprintSubjectPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of eprint subjects.
	 *
	 * @return the number of eprint subjects
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public int getEprintSubjectsCount() throws SystemException {
		return eprintSubjectPersistence.countAll();
	}

	/**
	 * Updates the eprint subject in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * @param eprintSubject the eprint subject
	 * @return the eprint subject that was updated
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public EprintSubject updateEprintSubject(EprintSubject eprintSubject)
		throws SystemException {
		return eprintSubjectPersistence.update(eprintSubject);
	}

	/**
	 * Returns the eprint local service.
	 *
	 * @return the eprint local service
	 */
	public com.idetronic.eprint.service.EprintLocalService getEprintLocalService() {
		return eprintLocalService;
	}

	/**
	 * Sets the eprint local service.
	 *
	 * @param eprintLocalService the eprint local service
	 */
	public void setEprintLocalService(
		com.idetronic.eprint.service.EprintLocalService eprintLocalService) {
		this.eprintLocalService = eprintLocalService;
	}

	/**
	 * Returns the eprint persistence.
	 *
	 * @return the eprint persistence
	 */
	public EprintPersistence getEprintPersistence() {
		return eprintPersistence;
	}

	/**
	 * Sets the eprint persistence.
	 *
	 * @param eprintPersistence the eprint persistence
	 */
	public void setEprintPersistence(EprintPersistence eprintPersistence) {
		this.eprintPersistence = eprintPersistence;
	}

	/**
	 * Returns the eprint finder.
	 *
	 * @return the eprint finder
	 */
	public EprintFinder getEprintFinder() {
		return eprintFinder;
	}

	/**
	 * Sets the eprint finder.
	 *
	 * @param eprintFinder the eprint finder
	 */
	public void setEprintFinder(EprintFinder eprintFinder) {
		this.eprintFinder = eprintFinder;
	}

	/**
	 * Returns the eprint division local service.
	 *
	 * @return the eprint division local service
	 */
	public com.idetronic.eprint.service.EprintDivisionLocalService getEprintDivisionLocalService() {
		return eprintDivisionLocalService;
	}

	/**
	 * Sets the eprint division local service.
	 *
	 * @param eprintDivisionLocalService the eprint division local service
	 */
	public void setEprintDivisionLocalService(
		com.idetronic.eprint.service.EprintDivisionLocalService eprintDivisionLocalService) {
		this.eprintDivisionLocalService = eprintDivisionLocalService;
	}

	/**
	 * Returns the eprint division persistence.
	 *
	 * @return the eprint division persistence
	 */
	public EprintDivisionPersistence getEprintDivisionPersistence() {
		return eprintDivisionPersistence;
	}

	/**
	 * Sets the eprint division persistence.
	 *
	 * @param eprintDivisionPersistence the eprint division persistence
	 */
	public void setEprintDivisionPersistence(
		EprintDivisionPersistence eprintDivisionPersistence) {
		this.eprintDivisionPersistence = eprintDivisionPersistence;
	}

	/**
	 * Returns the eprint static content local service.
	 *
	 * @return the eprint static content local service
	 */
	public com.idetronic.eprint.service.EprintStaticContentLocalService getEprintStaticContentLocalService() {
		return eprintStaticContentLocalService;
	}

	/**
	 * Sets the eprint static content local service.
	 *
	 * @param eprintStaticContentLocalService the eprint static content local service
	 */
	public void setEprintStaticContentLocalService(
		com.idetronic.eprint.service.EprintStaticContentLocalService eprintStaticContentLocalService) {
		this.eprintStaticContentLocalService = eprintStaticContentLocalService;
	}

	/**
	 * Returns the eprint static content persistence.
	 *
	 * @return the eprint static content persistence
	 */
	public EprintStaticContentPersistence getEprintStaticContentPersistence() {
		return eprintStaticContentPersistence;
	}

	/**
	 * Sets the eprint static content persistence.
	 *
	 * @param eprintStaticContentPersistence the eprint static content persistence
	 */
	public void setEprintStaticContentPersistence(
		EprintStaticContentPersistence eprintStaticContentPersistence) {
		this.eprintStaticContentPersistence = eprintStaticContentPersistence;
	}

	/**
	 * Returns the eprint subject local service.
	 *
	 * @return the eprint subject local service
	 */
	public com.idetronic.eprint.service.EprintSubjectLocalService getEprintSubjectLocalService() {
		return eprintSubjectLocalService;
	}

	/**
	 * Sets the eprint subject local service.
	 *
	 * @param eprintSubjectLocalService the eprint subject local service
	 */
	public void setEprintSubjectLocalService(
		com.idetronic.eprint.service.EprintSubjectLocalService eprintSubjectLocalService) {
		this.eprintSubjectLocalService = eprintSubjectLocalService;
	}

	/**
	 * Returns the eprint subject persistence.
	 *
	 * @return the eprint subject persistence
	 */
	public EprintSubjectPersistence getEprintSubjectPersistence() {
		return eprintSubjectPersistence;
	}

	/**
	 * Sets the eprint subject persistence.
	 *
	 * @param eprintSubjectPersistence the eprint subject persistence
	 */
	public void setEprintSubjectPersistence(
		EprintSubjectPersistence eprintSubjectPersistence) {
		this.eprintSubjectPersistence = eprintSubjectPersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public com.liferay.counter.service.CounterLocalService getCounterLocalService() {
		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(
		com.liferay.counter.service.CounterLocalService counterLocalService) {
		this.counterLocalService = counterLocalService;
	}

	/**
	 * Returns the resource local service.
	 *
	 * @return the resource local service
	 */
	public com.liferay.portal.service.ResourceLocalService getResourceLocalService() {
		return resourceLocalService;
	}

	/**
	 * Sets the resource local service.
	 *
	 * @param resourceLocalService the resource local service
	 */
	public void setResourceLocalService(
		com.liferay.portal.service.ResourceLocalService resourceLocalService) {
		this.resourceLocalService = resourceLocalService;
	}

	/**
	 * Returns the user local service.
	 *
	 * @return the user local service
	 */
	public com.liferay.portal.service.UserLocalService getUserLocalService() {
		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(
		com.liferay.portal.service.UserLocalService userLocalService) {
		this.userLocalService = userLocalService;
	}

	/**
	 * Returns the user remote service.
	 *
	 * @return the user remote service
	 */
	public com.liferay.portal.service.UserService getUserService() {
		return userService;
	}

	/**
	 * Sets the user remote service.
	 *
	 * @param userService the user remote service
	 */
	public void setUserService(
		com.liferay.portal.service.UserService userService) {
		this.userService = userService;
	}

	/**
	 * Returns the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	public void afterPropertiesSet() {
		Class<?> clazz = getClass();

		_classLoader = clazz.getClassLoader();

		PersistedModelLocalServiceRegistryUtil.register("com.idetronic.eprint.model.EprintSubject",
			eprintSubjectLocalService);
	}

	public void destroy() {
		PersistedModelLocalServiceRegistryUtil.unregister(
			"com.idetronic.eprint.model.EprintSubject");
	}

	/**
	 * Returns the Spring bean ID for this bean.
	 *
	 * @return the Spring bean ID for this bean
	 */
	@Override
	public String getBeanIdentifier() {
		return _beanIdentifier;
	}

	/**
	 * Sets the Spring bean ID for this bean.
	 *
	 * @param beanIdentifier the Spring bean ID for this bean
	 */
	@Override
	public void setBeanIdentifier(String beanIdentifier) {
		_beanIdentifier = beanIdentifier;
	}

	@Override
	public Object invokeMethod(String name, String[] parameterTypes,
		Object[] arguments) throws Throwable {
		Thread currentThread = Thread.currentThread();

		ClassLoader contextClassLoader = currentThread.getContextClassLoader();

		if (contextClassLoader != _classLoader) {
			currentThread.setContextClassLoader(_classLoader);
		}

		try {
			return _clpInvoker.invokeMethod(name, parameterTypes, arguments);
		}
		finally {
			if (contextClassLoader != _classLoader) {
				currentThread.setContextClassLoader(contextClassLoader);
			}
		}
	}

	protected Class<?> getModelClass() {
		return EprintSubject.class;
	}

	protected String getModelClassName() {
		return EprintSubject.class.getName();
	}

	/**
	 * Performs an SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) throws SystemException {
		try {
			DataSource dataSource = eprintSubjectPersistence.getDataSource();

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
					sql, new int[0]);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(type = com.idetronic.eprint.service.EprintLocalService.class)
	protected com.idetronic.eprint.service.EprintLocalService eprintLocalService;
	@BeanReference(type = EprintPersistence.class)
	protected EprintPersistence eprintPersistence;
	@BeanReference(type = EprintFinder.class)
	protected EprintFinder eprintFinder;
	@BeanReference(type = com.idetronic.eprint.service.EprintDivisionLocalService.class)
	protected com.idetronic.eprint.service.EprintDivisionLocalService eprintDivisionLocalService;
	@BeanReference(type = EprintDivisionPersistence.class)
	protected EprintDivisionPersistence eprintDivisionPersistence;
	@BeanReference(type = com.idetronic.eprint.service.EprintStaticContentLocalService.class)
	protected com.idetronic.eprint.service.EprintStaticContentLocalService eprintStaticContentLocalService;
	@BeanReference(type = EprintStaticContentPersistence.class)
	protected EprintStaticContentPersistence eprintStaticContentPersistence;
	@BeanReference(type = com.idetronic.eprint.service.EprintSubjectLocalService.class)
	protected com.idetronic.eprint.service.EprintSubjectLocalService eprintSubjectLocalService;
	@BeanReference(type = EprintSubjectPersistence.class)
	protected EprintSubjectPersistence eprintSubjectPersistence;
	@BeanReference(type = com.liferay.counter.service.CounterLocalService.class)
	protected com.liferay.counter.service.CounterLocalService counterLocalService;
	@BeanReference(type = com.liferay.portal.service.ResourceLocalService.class)
	protected com.liferay.portal.service.ResourceLocalService resourceLocalService;
	@BeanReference(type = com.liferay.portal.service.UserLocalService.class)
	protected com.liferay.portal.service.UserLocalService userLocalService;
	@BeanReference(type = com.liferay.portal.service.UserService.class)
	protected com.liferay.portal.service.UserService userService;
	@BeanReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;
	private String _beanIdentifier;
	private ClassLoader _classLoader;
	private EprintSubjectLocalServiceClpInvoker _clpInvoker = new EprintSubjectLocalServiceClpInvoker();
}