/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.idetronic.tazkirah.model.impl;

import com.idetronic.tazkirah.model.Tazkirah;
import com.idetronic.tazkirah.model.TazkirahModel;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;
import com.liferay.portal.util.PortalUtil;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the Tazkirah service. Represents a row in the &quot;tazkirah_Tazkirah&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.idetronic.tazkirah.model.TazkirahModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link TazkirahImpl}.
 * </p>
 *
 * @author Mazlan Mat
 * @see TazkirahImpl
 * @see com.idetronic.tazkirah.model.Tazkirah
 * @see com.idetronic.tazkirah.model.TazkirahModel
 * @generated
 */
public class TazkirahModelImpl extends BaseModelImpl<Tazkirah>
	implements TazkirahModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a tazkirah model instance should use the {@link com.idetronic.tazkirah.model.Tazkirah} interface instead.
	 */
	public static final String TABLE_NAME = "tazkirah_Tazkirah";
	public static final Object[][] TABLE_COLUMNS = {
			{ "tazkirahId", Types.BIGINT },
			{ "companyId", Types.BIGINT },
			{ "groupId", Types.BIGINT },
			{ "userId", Types.BIGINT },
			{ "userName", Types.VARCHAR },
			{ "createDate", Types.TIMESTAMP },
			{ "modifiedDate", Types.TIMESTAMP },
			{ "title", Types.VARCHAR },
			{ "content", Types.CLOB },
			{ "category", Types.VARCHAR },
			{ "status", Types.INTEGER }
		};
	public static final String TABLE_SQL_CREATE = "create table tazkirah_Tazkirah (tazkirahId LONG not null primary key,companyId LONG,groupId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,title VARCHAR(75) null,content TEXT null,category VARCHAR(75) null,status INTEGER)";
	public static final String TABLE_SQL_DROP = "drop table tazkirah_Tazkirah";
	public static final String ORDER_BY_JPQL = " ORDER BY tazkirah.tazkirahId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY tazkirah_Tazkirah.tazkirahId ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.idetronic.tazkirah.model.Tazkirah"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.idetronic.tazkirah.model.Tazkirah"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.idetronic.tazkirah.model.Tazkirah"),
			true);
	public static long CATEGORY_COLUMN_BITMASK = 1L;
	public static long TAZKIRAHID_COLUMN_BITMASK = 2L;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.idetronic.tazkirah.model.Tazkirah"));

	public TazkirahModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _tazkirahId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setTazkirahId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _tazkirahId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Tazkirah.class;
	}

	@Override
	public String getModelClassName() {
		return Tazkirah.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("tazkirahId", getTazkirahId());
		attributes.put("companyId", getCompanyId());
		attributes.put("groupId", getGroupId());
		attributes.put("userId", getUserId());
		attributes.put("userName", getUserName());
		attributes.put("createDate", getCreateDate());
		attributes.put("modifiedDate", getModifiedDate());
		attributes.put("title", getTitle());
		attributes.put("content", getContent());
		attributes.put("category", getCategory());
		attributes.put("status", getStatus());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long tazkirahId = (Long)attributes.get("tazkirahId");

		if (tazkirahId != null) {
			setTazkirahId(tazkirahId);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		Long groupId = (Long)attributes.get("groupId");

		if (groupId != null) {
			setGroupId(groupId);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		String userName = (String)attributes.get("userName");

		if (userName != null) {
			setUserName(userName);
		}

		Date createDate = (Date)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}

		Date modifiedDate = (Date)attributes.get("modifiedDate");

		if (modifiedDate != null) {
			setModifiedDate(modifiedDate);
		}

		String title = (String)attributes.get("title");

		if (title != null) {
			setTitle(title);
		}

		String content = (String)attributes.get("content");

		if (content != null) {
			setContent(content);
		}

		String category = (String)attributes.get("category");

		if (category != null) {
			setCategory(category);
		}

		Integer status = (Integer)attributes.get("status");

		if (status != null) {
			setStatus(status);
		}
	}

	@Override
	public long getTazkirahId() {
		return _tazkirahId;
	}

	@Override
	public void setTazkirahId(long tazkirahId) {
		_tazkirahId = tazkirahId;
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_companyId = companyId;
	}

	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_groupId = groupId;
	}

	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() throws SystemException {
		return PortalUtil.getUserValue(getUserId(), "uuid", _userUuid);
	}

	@Override
	public void setUserUuid(String userUuid) {
		_userUuid = userUuid;
	}

	@Override
	public String getUserName() {
		if (_userName == null) {
			return StringPool.BLANK;
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_modifiedDate = modifiedDate;
	}

	@Override
	public String getTitle() {
		if (_title == null) {
			return StringPool.BLANK;
		}
		else {
			return _title;
		}
	}

	@Override
	public void setTitle(String title) {
		_title = title;
	}

	@Override
	public String getContent() {
		if (_content == null) {
			return StringPool.BLANK;
		}
		else {
			return _content;
		}
	}

	@Override
	public void setContent(String content) {
		_content = content;
	}

	@Override
	public String getCategory() {
		if (_category == null) {
			return StringPool.BLANK;
		}
		else {
			return _category;
		}
	}

	@Override
	public void setCategory(String category) {
		_columnBitmask |= CATEGORY_COLUMN_BITMASK;

		if (_originalCategory == null) {
			_originalCategory = _category;
		}

		_category = category;
	}

	public String getOriginalCategory() {
		return GetterUtil.getString(_originalCategory);
	}

	@Override
	public int getStatus() {
		return _status;
	}

	@Override
	public void setStatus(int status) {
		_status = status;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
			Tazkirah.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Tazkirah toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (Tazkirah)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		TazkirahImpl tazkirahImpl = new TazkirahImpl();

		tazkirahImpl.setTazkirahId(getTazkirahId());
		tazkirahImpl.setCompanyId(getCompanyId());
		tazkirahImpl.setGroupId(getGroupId());
		tazkirahImpl.setUserId(getUserId());
		tazkirahImpl.setUserName(getUserName());
		tazkirahImpl.setCreateDate(getCreateDate());
		tazkirahImpl.setModifiedDate(getModifiedDate());
		tazkirahImpl.setTitle(getTitle());
		tazkirahImpl.setContent(getContent());
		tazkirahImpl.setCategory(getCategory());
		tazkirahImpl.setStatus(getStatus());

		tazkirahImpl.resetOriginalValues();

		return tazkirahImpl;
	}

	@Override
	public int compareTo(Tazkirah tazkirah) {
		long primaryKey = tazkirah.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof Tazkirah)) {
			return false;
		}

		Tazkirah tazkirah = (Tazkirah)obj;

		long primaryKey = tazkirah.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		TazkirahModelImpl tazkirahModelImpl = this;

		tazkirahModelImpl._originalCategory = tazkirahModelImpl._category;

		tazkirahModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<Tazkirah> toCacheModel() {
		TazkirahCacheModel tazkirahCacheModel = new TazkirahCacheModel();

		tazkirahCacheModel.tazkirahId = getTazkirahId();

		tazkirahCacheModel.companyId = getCompanyId();

		tazkirahCacheModel.groupId = getGroupId();

		tazkirahCacheModel.userId = getUserId();

		tazkirahCacheModel.userName = getUserName();

		String userName = tazkirahCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			tazkirahCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			tazkirahCacheModel.createDate = createDate.getTime();
		}
		else {
			tazkirahCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			tazkirahCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			tazkirahCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		tazkirahCacheModel.title = getTitle();

		String title = tazkirahCacheModel.title;

		if ((title != null) && (title.length() == 0)) {
			tazkirahCacheModel.title = null;
		}

		tazkirahCacheModel.content = getContent();

		String content = tazkirahCacheModel.content;

		if ((content != null) && (content.length() == 0)) {
			tazkirahCacheModel.content = null;
		}

		tazkirahCacheModel.category = getCategory();

		String category = tazkirahCacheModel.category;

		if ((category != null) && (category.length() == 0)) {
			tazkirahCacheModel.category = null;
		}

		tazkirahCacheModel.status = getStatus();

		return tazkirahCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(23);

		sb.append("{tazkirahId=");
		sb.append(getTazkirahId());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", groupId=");
		sb.append(getGroupId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", userName=");
		sb.append(getUserName());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append(", title=");
		sb.append(getTitle());
		sb.append(", content=");
		sb.append(getContent());
		sb.append(", category=");
		sb.append(getCategory());
		sb.append(", status=");
		sb.append(getStatus());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(37);

		sb.append("<model><model-name>");
		sb.append("com.idetronic.tazkirah.model.Tazkirah");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>tazkirahId</column-name><column-value><![CDATA[");
		sb.append(getTazkirahId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>groupId</column-name><column-value><![CDATA[");
		sb.append(getGroupId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userName</column-name><column-value><![CDATA[");
		sb.append(getUserName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>title</column-name><column-value><![CDATA[");
		sb.append(getTitle());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>content</column-name><column-value><![CDATA[");
		sb.append(getContent());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>category</column-name><column-value><![CDATA[");
		sb.append(getCategory());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>status</column-name><column-value><![CDATA[");
		sb.append(getStatus());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = Tazkirah.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			Tazkirah.class
		};
	private long _tazkirahId;
	private long _companyId;
	private long _groupId;
	private long _userId;
	private String _userUuid;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private String _title;
	private String _content;
	private String _category;
	private String _originalCategory;
	private int _status;
	private long _columnBitmask;
	private Tazkirah _escapedModel;
}