/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.idetronic.subur.model.impl;

import com.idetronic.subur.model.MetadataPropertyValue;
import com.idetronic.subur.service.MetadataPropertyValueLocalServiceUtil;

import com.liferay.portal.kernel.exception.SystemException;

/**
 * The extended model base implementation for the MetadataPropertyValue service. Represents a row in the &quot;Subur_MetadataPropertyValue&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link MetadataPropertyValueImpl}.
 * </p>
 *
 * @author Mazlan Mat
 * @see MetadataPropertyValueImpl
 * @see com.idetronic.subur.model.MetadataPropertyValue
 * @generated
 */
public abstract class MetadataPropertyValueBaseImpl
	extends MetadataPropertyValueModelImpl implements MetadataPropertyValue {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a metadata property value model instance should use the {@link MetadataPropertyValue} interface instead.
	 */
	@Override
	public void persist() throws SystemException {
		if (this.isNew()) {
			MetadataPropertyValueLocalServiceUtil.addMetadataPropertyValue(this);
		}
		else {
			MetadataPropertyValueLocalServiceUtil.updateMetadataPropertyValue(this);
		}
	}
}