/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.idetronic.subur.model.impl;

import com.idetronic.subur.model.StatDownloadItemType;
import com.idetronic.subur.model.StatDownloadItemTypeModel;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import java.io.Serializable;

import java.sql.Types;

import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the StatDownloadItemType service. Represents a row in the &quot;Subur_StatDownloadItemType&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.idetronic.subur.model.StatDownloadItemTypeModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link StatDownloadItemTypeImpl}.
 * </p>
 *
 * @author Mazlan Mat
 * @see StatDownloadItemTypeImpl
 * @see com.idetronic.subur.model.StatDownloadItemType
 * @see com.idetronic.subur.model.StatDownloadItemTypeModel
 * @generated
 */
public class StatDownloadItemTypeModelImpl extends BaseModelImpl<StatDownloadItemType>
	implements StatDownloadItemTypeModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a stat download item type model instance should use the {@link com.idetronic.subur.model.StatDownloadItemType} interface instead.
	 */
	public static final String TABLE_NAME = "Subur_StatDownloadItemType";
	public static final Object[][] TABLE_COLUMNS = {
			{ "id_", Types.BIGINT },
			{ "perMonth", Types.INTEGER },
			{ "perYear", Types.INTEGER },
			{ "itemTypeId", Types.BIGINT }
		};
	public static final String TABLE_SQL_CREATE = "create table Subur_StatDownloadItemType (id_ LONG not null primary key,perMonth INTEGER,perYear INTEGER,itemTypeId LONG)";
	public static final String TABLE_SQL_DROP = "drop table Subur_StatDownloadItemType";
	public static final String ORDER_BY_JPQL = " ORDER BY statDownloadItemType.id ASC";
	public static final String ORDER_BY_SQL = " ORDER BY Subur_StatDownloadItemType.id_ ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.idetronic.subur.model.StatDownloadItemType"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.idetronic.subur.model.StatDownloadItemType"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.idetronic.subur.model.StatDownloadItemType"),
			true);
	public static long ITEMTYPEID_COLUMN_BITMASK = 1L;
	public static long ID_COLUMN_BITMASK = 2L;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.idetronic.subur.model.StatDownloadItemType"));

	public StatDownloadItemTypeModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _id;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return StatDownloadItemType.class;
	}

	@Override
	public String getModelClassName() {
		return StatDownloadItemType.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("id", getId());
		attributes.put("perMonth", getPerMonth());
		attributes.put("perYear", getPerYear());
		attributes.put("itemTypeId", getItemTypeId());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long id = (Long)attributes.get("id");

		if (id != null) {
			setId(id);
		}

		Integer perMonth = (Integer)attributes.get("perMonth");

		if (perMonth != null) {
			setPerMonth(perMonth);
		}

		Integer perYear = (Integer)attributes.get("perYear");

		if (perYear != null) {
			setPerYear(perYear);
		}

		Long itemTypeId = (Long)attributes.get("itemTypeId");

		if (itemTypeId != null) {
			setItemTypeId(itemTypeId);
		}
	}

	@Override
	public long getId() {
		return _id;
	}

	@Override
	public void setId(long id) {
		_id = id;
	}

	@Override
	public int getPerMonth() {
		return _perMonth;
	}

	@Override
	public void setPerMonth(int perMonth) {
		_perMonth = perMonth;
	}

	@Override
	public int getPerYear() {
		return _perYear;
	}

	@Override
	public void setPerYear(int perYear) {
		_perYear = perYear;
	}

	@Override
	public long getItemTypeId() {
		return _itemTypeId;
	}

	@Override
	public void setItemTypeId(long itemTypeId) {
		_columnBitmask |= ITEMTYPEID_COLUMN_BITMASK;

		if (!_setOriginalItemTypeId) {
			_setOriginalItemTypeId = true;

			_originalItemTypeId = _itemTypeId;
		}

		_itemTypeId = itemTypeId;
	}

	public long getOriginalItemTypeId() {
		return _originalItemTypeId;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			StatDownloadItemType.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public StatDownloadItemType toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (StatDownloadItemType)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		StatDownloadItemTypeImpl statDownloadItemTypeImpl = new StatDownloadItemTypeImpl();

		statDownloadItemTypeImpl.setId(getId());
		statDownloadItemTypeImpl.setPerMonth(getPerMonth());
		statDownloadItemTypeImpl.setPerYear(getPerYear());
		statDownloadItemTypeImpl.setItemTypeId(getItemTypeId());

		statDownloadItemTypeImpl.resetOriginalValues();

		return statDownloadItemTypeImpl;
	}

	@Override
	public int compareTo(StatDownloadItemType statDownloadItemType) {
		long primaryKey = statDownloadItemType.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof StatDownloadItemType)) {
			return false;
		}

		StatDownloadItemType statDownloadItemType = (StatDownloadItemType)obj;

		long primaryKey = statDownloadItemType.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		StatDownloadItemTypeModelImpl statDownloadItemTypeModelImpl = this;

		statDownloadItemTypeModelImpl._originalItemTypeId = statDownloadItemTypeModelImpl._itemTypeId;

		statDownloadItemTypeModelImpl._setOriginalItemTypeId = false;

		statDownloadItemTypeModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<StatDownloadItemType> toCacheModel() {
		StatDownloadItemTypeCacheModel statDownloadItemTypeCacheModel = new StatDownloadItemTypeCacheModel();

		statDownloadItemTypeCacheModel.id = getId();

		statDownloadItemTypeCacheModel.perMonth = getPerMonth();

		statDownloadItemTypeCacheModel.perYear = getPerYear();

		statDownloadItemTypeCacheModel.itemTypeId = getItemTypeId();

		return statDownloadItemTypeCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(9);

		sb.append("{id=");
		sb.append(getId());
		sb.append(", perMonth=");
		sb.append(getPerMonth());
		sb.append(", perYear=");
		sb.append(getPerYear());
		sb.append(", itemTypeId=");
		sb.append(getItemTypeId());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(16);

		sb.append("<model><model-name>");
		sb.append("com.idetronic.subur.model.StatDownloadItemType");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>id</column-name><column-value><![CDATA[");
		sb.append(getId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>perMonth</column-name><column-value><![CDATA[");
		sb.append(getPerMonth());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>perYear</column-name><column-value><![CDATA[");
		sb.append(getPerYear());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>itemTypeId</column-name><column-value><![CDATA[");
		sb.append(getItemTypeId());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = StatDownloadItemType.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			StatDownloadItemType.class
		};
	private long _id;
	private int _perMonth;
	private int _perYear;
	private long _itemTypeId;
	private long _originalItemTypeId;
	private boolean _setOriginalItemTypeId;
	private long _columnBitmask;
	private StatDownloadItemType _escapedModel;
}