/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.idetronic.ruangj.service.base;

import com.idetronic.ruangj.model.ItemFileEntry;
import com.idetronic.ruangj.service.ItemFileEntryService;
import com.idetronic.ruangj.service.persistence.ItemFileEntryPersistence;
import com.idetronic.ruangj.service.persistence.ItemPersistence;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.bean.IdentifiableBean;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.service.BaseServiceImpl;
import com.liferay.portal.service.persistence.UserPersistence;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the item file entry remote service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.idetronic.ruangj.service.impl.ItemFileEntryServiceImpl}.
 * </p>
 *
 * @author Mazlan Mat
 * @see com.idetronic.ruangj.service.impl.ItemFileEntryServiceImpl
 * @see com.idetronic.ruangj.service.ItemFileEntryServiceUtil
 * @generated
 */
public abstract class ItemFileEntryServiceBaseImpl extends BaseServiceImpl
	implements ItemFileEntryService, IdentifiableBean {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Always use {@link com.idetronic.ruangj.service.ItemFileEntryServiceUtil} to access the item file entry remote service.
	 */

	/**
	 * Returns the item local service.
	 *
	 * @return the item local service
	 */
	public com.idetronic.ruangj.service.ItemLocalService getItemLocalService() {
		return itemLocalService;
	}

	/**
	 * Sets the item local service.
	 *
	 * @param itemLocalService the item local service
	 */
	public void setItemLocalService(
		com.idetronic.ruangj.service.ItemLocalService itemLocalService) {
		this.itemLocalService = itemLocalService;
	}

	/**
	 * Returns the item persistence.
	 *
	 * @return the item persistence
	 */
	public ItemPersistence getItemPersistence() {
		return itemPersistence;
	}

	/**
	 * Sets the item persistence.
	 *
	 * @param itemPersistence the item persistence
	 */
	public void setItemPersistence(ItemPersistence itemPersistence) {
		this.itemPersistence = itemPersistence;
	}

	/**
	 * Returns the item file entry local service.
	 *
	 * @return the item file entry local service
	 */
	public com.idetronic.ruangj.service.ItemFileEntryLocalService getItemFileEntryLocalService() {
		return itemFileEntryLocalService;
	}

	/**
	 * Sets the item file entry local service.
	 *
	 * @param itemFileEntryLocalService the item file entry local service
	 */
	public void setItemFileEntryLocalService(
		com.idetronic.ruangj.service.ItemFileEntryLocalService itemFileEntryLocalService) {
		this.itemFileEntryLocalService = itemFileEntryLocalService;
	}

	/**
	 * Returns the item file entry remote service.
	 *
	 * @return the item file entry remote service
	 */
	public com.idetronic.ruangj.service.ItemFileEntryService getItemFileEntryService() {
		return itemFileEntryService;
	}

	/**
	 * Sets the item file entry remote service.
	 *
	 * @param itemFileEntryService the item file entry remote service
	 */
	public void setItemFileEntryService(
		com.idetronic.ruangj.service.ItemFileEntryService itemFileEntryService) {
		this.itemFileEntryService = itemFileEntryService;
	}

	/**
	 * Returns the item file entry persistence.
	 *
	 * @return the item file entry persistence
	 */
	public ItemFileEntryPersistence getItemFileEntryPersistence() {
		return itemFileEntryPersistence;
	}

	/**
	 * Sets the item file entry persistence.
	 *
	 * @param itemFileEntryPersistence the item file entry persistence
	 */
	public void setItemFileEntryPersistence(
		ItemFileEntryPersistence itemFileEntryPersistence) {
		this.itemFileEntryPersistence = itemFileEntryPersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public com.liferay.counter.service.CounterLocalService getCounterLocalService() {
		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(
		com.liferay.counter.service.CounterLocalService counterLocalService) {
		this.counterLocalService = counterLocalService;
	}

	/**
	 * Returns the resource local service.
	 *
	 * @return the resource local service
	 */
	public com.liferay.portal.service.ResourceLocalService getResourceLocalService() {
		return resourceLocalService;
	}

	/**
	 * Sets the resource local service.
	 *
	 * @param resourceLocalService the resource local service
	 */
	public void setResourceLocalService(
		com.liferay.portal.service.ResourceLocalService resourceLocalService) {
		this.resourceLocalService = resourceLocalService;
	}

	/**
	 * Returns the user local service.
	 *
	 * @return the user local service
	 */
	public com.liferay.portal.service.UserLocalService getUserLocalService() {
		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(
		com.liferay.portal.service.UserLocalService userLocalService) {
		this.userLocalService = userLocalService;
	}

	/**
	 * Returns the user remote service.
	 *
	 * @return the user remote service
	 */
	public com.liferay.portal.service.UserService getUserService() {
		return userService;
	}

	/**
	 * Sets the user remote service.
	 *
	 * @param userService the user remote service
	 */
	public void setUserService(
		com.liferay.portal.service.UserService userService) {
		this.userService = userService;
	}

	/**
	 * Returns the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	public void afterPropertiesSet() {
		Class<?> clazz = getClass();

		_classLoader = clazz.getClassLoader();
	}

	public void destroy() {
	}

	/**
	 * Returns the Spring bean ID for this bean.
	 *
	 * @return the Spring bean ID for this bean
	 */
	@Override
	public String getBeanIdentifier() {
		return _beanIdentifier;
	}

	/**
	 * Sets the Spring bean ID for this bean.
	 *
	 * @param beanIdentifier the Spring bean ID for this bean
	 */
	@Override
	public void setBeanIdentifier(String beanIdentifier) {
		_beanIdentifier = beanIdentifier;
	}

	@Override
	public Object invokeMethod(String name, String[] parameterTypes,
		Object[] arguments) throws Throwable {
		Thread currentThread = Thread.currentThread();

		ClassLoader contextClassLoader = currentThread.getContextClassLoader();

		if (contextClassLoader != _classLoader) {
			currentThread.setContextClassLoader(_classLoader);
		}

		try {
			return _clpInvoker.invokeMethod(name, parameterTypes, arguments);
		}
		finally {
			if (contextClassLoader != _classLoader) {
				currentThread.setContextClassLoader(contextClassLoader);
			}
		}
	}

	protected Class<?> getModelClass() {
		return ItemFileEntry.class;
	}

	protected String getModelClassName() {
		return ItemFileEntry.class.getName();
	}

	/**
	 * Performs an SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) throws SystemException {
		try {
			DataSource dataSource = itemFileEntryPersistence.getDataSource();

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
					sql, new int[0]);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(type = com.idetronic.ruangj.service.ItemLocalService.class)
	protected com.idetronic.ruangj.service.ItemLocalService itemLocalService;
	@BeanReference(type = ItemPersistence.class)
	protected ItemPersistence itemPersistence;
	@BeanReference(type = com.idetronic.ruangj.service.ItemFileEntryLocalService.class)
	protected com.idetronic.ruangj.service.ItemFileEntryLocalService itemFileEntryLocalService;
	@BeanReference(type = com.idetronic.ruangj.service.ItemFileEntryService.class)
	protected com.idetronic.ruangj.service.ItemFileEntryService itemFileEntryService;
	@BeanReference(type = ItemFileEntryPersistence.class)
	protected ItemFileEntryPersistence itemFileEntryPersistence;
	@BeanReference(type = com.liferay.counter.service.CounterLocalService.class)
	protected com.liferay.counter.service.CounterLocalService counterLocalService;
	@BeanReference(type = com.liferay.portal.service.ResourceLocalService.class)
	protected com.liferay.portal.service.ResourceLocalService resourceLocalService;
	@BeanReference(type = com.liferay.portal.service.UserLocalService.class)
	protected com.liferay.portal.service.UserLocalService userLocalService;
	@BeanReference(type = com.liferay.portal.service.UserService.class)
	protected com.liferay.portal.service.UserService userService;
	@BeanReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;
	private String _beanIdentifier;
	private ClassLoader _classLoader;
	private ItemFileEntryServiceClpInvoker _clpInvoker = new ItemFileEntryServiceClpInvoker();
}