/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.idetronic.eprint.model;

import com.idetronic.eprint.service.persistence.EprintDivisionPK;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the EprintDivision service. Represents a row in the &quot;Eprints_EprintDivision&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.idetronic.eprint.model.impl.EprintDivisionModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.idetronic.eprint.model.impl.EprintDivisionImpl}.
 * </p>
 *
 * @author Mazlan Mat
 * @see EprintDivision
 * @see com.idetronic.eprint.model.impl.EprintDivisionImpl
 * @see com.idetronic.eprint.model.impl.EprintDivisionModelImpl
 * @generated
 */
public interface EprintDivisionModel extends BaseModel<EprintDivision> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a eprint division model instance should use the {@link EprintDivision} interface instead.
	 */

	/**
	 * Returns the primary key of this eprint division.
	 *
	 * @return the primary key of this eprint division
	 */
	public EprintDivisionPK getPrimaryKey();

	/**
	 * Sets the primary key of this eprint division.
	 *
	 * @param primaryKey the primary key of this eprint division
	 */
	public void setPrimaryKey(EprintDivisionPK primaryKey);

	/**
	 * Returns the eprint ID of this eprint division.
	 *
	 * @return the eprint ID of this eprint division
	 */
	public long getEprintId();

	/**
	 * Sets the eprint ID of this eprint division.
	 *
	 * @param eprintId the eprint ID of this eprint division
	 */
	public void setEprintId(long eprintId);

	/**
	 * Returns the division ID of this eprint division.
	 *
	 * @return the division ID of this eprint division
	 */
	@AutoEscape
	public String getDivisionId();

	/**
	 * Sets the division ID of this eprint division.
	 *
	 * @param divisionId the division ID of this eprint division
	 */
	public void setDivisionId(String divisionId);

	/**
	 * Returns the division name of this eprint division.
	 *
	 * @return the division name of this eprint division
	 */
	@AutoEscape
	public String getDivisionName();

	/**
	 * Sets the division name of this eprint division.
	 *
	 * @param divisionName the division name of this eprint division
	 */
	public void setDivisionName(String divisionName);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(EprintDivision eprintDivision);

	@Override
	public int hashCode();

	@Override
	public CacheModel<EprintDivision> toCacheModel();

	@Override
	public EprintDivision toEscapedModel();

	@Override
	public EprintDivision toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}