/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.idetronic.portlet.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.GroupedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the FAQEntry service. Represents a row in the &quot;FAQ_FAQEntry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.idetronic.portlet.model.impl.FAQEntryModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.idetronic.portlet.model.impl.FAQEntryImpl}.
 * </p>
 *
 * @author Idetronic Sdn Bhd
 * @see FAQEntry
 * @see com.idetronic.portlet.model.impl.FAQEntryImpl
 * @see com.idetronic.portlet.model.impl.FAQEntryModelImpl
 * @generated
 */
public interface FAQEntryModel extends BaseModel<FAQEntry>, GroupedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a f a q entry model instance should use the {@link FAQEntry} interface instead.
	 */

	/**
	 * Returns the primary key of this f a q entry.
	 *
	 * @return the primary key of this f a q entry
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this f a q entry.
	 *
	 * @param primaryKey the primary key of this f a q entry
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the entry ID of this f a q entry.
	 *
	 * @return the entry ID of this f a q entry
	 */
	public long getEntryId();

	/**
	 * Sets the entry ID of this f a q entry.
	 *
	 * @param entryId the entry ID of this f a q entry
	 */
	public void setEntryId(long entryId);

	/**
	 * Returns the company ID of this f a q entry.
	 *
	 * @return the company ID of this f a q entry
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this f a q entry.
	 *
	 * @param companyId the company ID of this f a q entry
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the group ID of this f a q entry.
	 *
	 * @return the group ID of this f a q entry
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this f a q entry.
	 *
	 * @param groupId the group ID of this f a q entry
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the user ID of this f a q entry.
	 *
	 * @return the user ID of this f a q entry
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this f a q entry.
	 *
	 * @param userId the user ID of this f a q entry
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this f a q entry.
	 *
	 * @return the user uuid of this f a q entry
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this f a q entry.
	 *
	 * @param userUuid the user uuid of this f a q entry
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this f a q entry.
	 *
	 * @return the user name of this f a q entry
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this f a q entry.
	 *
	 * @param userName the user name of this f a q entry
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this f a q entry.
	 *
	 * @return the create date of this f a q entry
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this f a q entry.
	 *
	 * @param createDate the create date of this f a q entry
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this f a q entry.
	 *
	 * @return the modified date of this f a q entry
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this f a q entry.
	 *
	 * @param modifiedDate the modified date of this f a q entry
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the question of this f a q entry.
	 *
	 * @return the question of this f a q entry
	 */
	@AutoEscape
	public String getQuestion();

	/**
	 * Sets the question of this f a q entry.
	 *
	 * @param question the question of this f a q entry
	 */
	public void setQuestion(String question);

	/**
	 * Returns the category of this f a q entry.
	 *
	 * @return the category of this f a q entry
	 */
	@AutoEscape
	public String getCategory();

	/**
	 * Sets the category of this f a q entry.
	 *
	 * @param category the category of this f a q entry
	 */
	public void setCategory(String category);

	/**
	 * Returns the answer of this f a q entry.
	 *
	 * @return the answer of this f a q entry
	 */
	@AutoEscape
	public String getAnswer();

	/**
	 * Sets the answer of this f a q entry.
	 *
	 * @param answer the answer of this f a q entry
	 */
	public void setAnswer(String answer);

	/**
	 * Returns the isactive of this f a q entry.
	 *
	 * @return the isactive of this f a q entry
	 */
	public Boolean getIsactive();

	/**
	 * Sets the isactive of this f a q entry.
	 *
	 * @param isactive the isactive of this f a q entry
	 */
	public void setIsactive(Boolean isactive);

	/**
	 * Returns the display order of this f a q entry.
	 *
	 * @return the display order of this f a q entry
	 */
	public long getDisplayOrder();

	/**
	 * Sets the display order of this f a q entry.
	 *
	 * @param displayOrder the display order of this f a q entry
	 */
	public void setDisplayOrder(long displayOrder);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(FAQEntry faqEntry);

	@Override
	public int hashCode();

	@Override
	public CacheModel<FAQEntry> toCacheModel();

	@Override
	public FAQEntry toEscapedModel();

	@Override
	public FAQEntry toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}