/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.idetronic.portlet.serviceexperience.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.AuditedModel;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the ServiceExperience service. Represents a row in the &quot;ide_ServiceExperience&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.idetronic.portlet.serviceexperience.model.impl.ServiceExperienceModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.idetronic.portlet.serviceexperience.model.impl.ServiceExperienceImpl}.
 * </p>
 *
 * @author Mazlan Mat
 * @see ServiceExperience
 * @see com.idetronic.portlet.serviceexperience.model.impl.ServiceExperienceImpl
 * @see com.idetronic.portlet.serviceexperience.model.impl.ServiceExperienceModelImpl
 * @generated
 */
public interface ServiceExperienceModel extends AuditedModel,
	BaseModel<ServiceExperience> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a service experience model instance should use the {@link ServiceExperience} interface instead.
	 */

	/**
	 * Returns the primary key of this service experience.
	 *
	 * @return the primary key of this service experience
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this service experience.
	 *
	 * @param primaryKey the primary key of this service experience
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the service experience ID of this service experience.
	 *
	 * @return the service experience ID of this service experience
	 */
	public long getServiceExperienceId();

	/**
	 * Sets the service experience ID of this service experience.
	 *
	 * @param serviceExperienceId the service experience ID of this service experience
	 */
	public void setServiceExperienceId(long serviceExperienceId);

	/**
	 * Returns the company ID of this service experience.
	 *
	 * @return the company ID of this service experience
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this service experience.
	 *
	 * @param companyId the company ID of this service experience
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this service experience.
	 *
	 * @return the user ID of this service experience
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this service experience.
	 *
	 * @param userId the user ID of this service experience
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this service experience.
	 *
	 * @return the user uuid of this service experience
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this service experience.
	 *
	 * @param userUuid the user uuid of this service experience
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this service experience.
	 *
	 * @return the user name of this service experience
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this service experience.
	 *
	 * @param userName the user name of this service experience
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this service experience.
	 *
	 * @return the create date of this service experience
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this service experience.
	 *
	 * @param createDate the create date of this service experience
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this service experience.
	 *
	 * @return the modified date of this service experience
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this service experience.
	 *
	 * @param modifiedDate the modified date of this service experience
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the start date of this service experience.
	 *
	 * @return the start date of this service experience
	 */
	public Date getStartDate();

	/**
	 * Sets the start date of this service experience.
	 *
	 * @param startDate the start date of this service experience
	 */
	public void setStartDate(Date startDate);

	/**
	 * Returns the title of this service experience.
	 *
	 * @return the title of this service experience
	 */
	@AutoEscape
	public String getTitle();

	/**
	 * Sets the title of this service experience.
	 *
	 * @param title the title of this service experience
	 */
	public void setTitle(String title);

	/**
	 * Returns the end date of this service experience.
	 *
	 * @return the end date of this service experience
	 */
	public Date getEndDate();

	/**
	 * Sets the end date of this service experience.
	 *
	 * @param endDate the end date of this service experience
	 */
	public void setEndDate(Date endDate);

	/**
	 * Returns the service data of this service experience.
	 *
	 * @return the service data of this service experience
	 */
	@AutoEscape
	public String getServiceData();

	/**
	 * Sets the service data of this service experience.
	 *
	 * @param serviceData the service data of this service experience
	 */
	public void setServiceData(String serviceData);

	/**
	 * Returns the status of this service experience.
	 *
	 * @return the status of this service experience
	 */
	public int getStatus();

	/**
	 * Sets the status of this service experience.
	 *
	 * @param status the status of this service experience
	 */
	public void setStatus(int status);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(ServiceExperience serviceExperience);

	@Override
	public int hashCode();

	@Override
	public CacheModel<ServiceExperience> toCacheModel();

	@Override
	public ServiceExperience toEscapedModel();

	@Override
	public ServiceExperience toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}