/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.idetronic.portlet.model.impl;

import com.idetronic.portlet.model.ExpertiseTag;
import com.idetronic.portlet.model.ExpertiseTagModel;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;
import com.liferay.portal.util.PortalUtil;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the ExpertiseTag service. Represents a row in the &quot;ide_ExpertiseTag&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.idetronic.portlet.model.ExpertiseTagModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ExpertiseTagImpl}.
 * </p>
 *
 * @author Mazlan Mat
 * @see ExpertiseTagImpl
 * @see com.idetronic.portlet.model.ExpertiseTag
 * @see com.idetronic.portlet.model.ExpertiseTagModel
 * @generated
 */
public class ExpertiseTagModelImpl extends BaseModelImpl<ExpertiseTag>
	implements ExpertiseTagModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a expertise tag model instance should use the {@link com.idetronic.portlet.model.ExpertiseTag} interface instead.
	 */
	public static final String TABLE_NAME = "ide_ExpertiseTag";
	public static final Object[][] TABLE_COLUMNS = {
			{ "tagId", Types.BIGINT },
			{ "groupId", Types.BIGINT },
			{ "companyId", Types.BIGINT },
			{ "userId", Types.BIGINT },
			{ "userName", Types.VARCHAR },
			{ "createDate", Types.TIMESTAMP },
			{ "modifiedDate", Types.TIMESTAMP },
			{ "tagName", Types.VARCHAR },
			{ "userCount", Types.INTEGER }
		};
	public static final String TABLE_SQL_CREATE = "create table ide_ExpertiseTag (tagId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,tagName VARCHAR(75) null,userCount INTEGER)";
	public static final String TABLE_SQL_DROP = "drop table ide_ExpertiseTag";
	public static final String ORDER_BY_JPQL = " ORDER BY expertiseTag.tagId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY ide_ExpertiseTag.tagId ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.idetronic.portlet.model.ExpertiseTag"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.idetronic.portlet.model.ExpertiseTag"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.idetronic.portlet.model.ExpertiseTag"),
			true);
	public static long TAGNAME_COLUMN_BITMASK = 1L;
	public static long TAGID_COLUMN_BITMASK = 2L;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.idetronic.portlet.model.ExpertiseTag"));

	public ExpertiseTagModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _tagId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setTagId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _tagId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return ExpertiseTag.class;
	}

	@Override
	public String getModelClassName() {
		return ExpertiseTag.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("tagId", getTagId());
		attributes.put("groupId", getGroupId());
		attributes.put("companyId", getCompanyId());
		attributes.put("userId", getUserId());
		attributes.put("userName", getUserName());
		attributes.put("createDate", getCreateDate());
		attributes.put("modifiedDate", getModifiedDate());
		attributes.put("tagName", getTagName());
		attributes.put("userCount", getUserCount());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long tagId = (Long)attributes.get("tagId");

		if (tagId != null) {
			setTagId(tagId);
		}

		Long groupId = (Long)attributes.get("groupId");

		if (groupId != null) {
			setGroupId(groupId);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		String userName = (String)attributes.get("userName");

		if (userName != null) {
			setUserName(userName);
		}

		Date createDate = (Date)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}

		Date modifiedDate = (Date)attributes.get("modifiedDate");

		if (modifiedDate != null) {
			setModifiedDate(modifiedDate);
		}

		String tagName = (String)attributes.get("tagName");

		if (tagName != null) {
			setTagName(tagName);
		}

		Integer userCount = (Integer)attributes.get("userCount");

		if (userCount != null) {
			setUserCount(userCount);
		}
	}

	@Override
	public long getTagId() {
		return _tagId;
	}

	@Override
	public void setTagId(long tagId) {
		_tagId = tagId;
	}

	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_groupId = groupId;
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_companyId = companyId;
	}

	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() throws SystemException {
		return PortalUtil.getUserValue(getUserId(), "uuid", _userUuid);
	}

	@Override
	public void setUserUuid(String userUuid) {
		_userUuid = userUuid;
	}

	@Override
	public String getUserName() {
		if (_userName == null) {
			return StringPool.BLANK;
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_modifiedDate = modifiedDate;
	}

	@Override
	public String getTagName() {
		if (_tagName == null) {
			return StringPool.BLANK;
		}
		else {
			return _tagName;
		}
	}

	@Override
	public void setTagName(String tagName) {
		_columnBitmask |= TAGNAME_COLUMN_BITMASK;

		if (_originalTagName == null) {
			_originalTagName = _tagName;
		}

		_tagName = tagName;
	}

	public String getOriginalTagName() {
		return GetterUtil.getString(_originalTagName);
	}

	@Override
	public int getUserCount() {
		return _userCount;
	}

	@Override
	public void setUserCount(int userCount) {
		_userCount = userCount;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
			ExpertiseTag.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public ExpertiseTag toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (ExpertiseTag)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		ExpertiseTagImpl expertiseTagImpl = new ExpertiseTagImpl();

		expertiseTagImpl.setTagId(getTagId());
		expertiseTagImpl.setGroupId(getGroupId());
		expertiseTagImpl.setCompanyId(getCompanyId());
		expertiseTagImpl.setUserId(getUserId());
		expertiseTagImpl.setUserName(getUserName());
		expertiseTagImpl.setCreateDate(getCreateDate());
		expertiseTagImpl.setModifiedDate(getModifiedDate());
		expertiseTagImpl.setTagName(getTagName());
		expertiseTagImpl.setUserCount(getUserCount());

		expertiseTagImpl.resetOriginalValues();

		return expertiseTagImpl;
	}

	@Override
	public int compareTo(ExpertiseTag expertiseTag) {
		long primaryKey = expertiseTag.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof ExpertiseTag)) {
			return false;
		}

		ExpertiseTag expertiseTag = (ExpertiseTag)obj;

		long primaryKey = expertiseTag.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		ExpertiseTagModelImpl expertiseTagModelImpl = this;

		expertiseTagModelImpl._originalTagName = expertiseTagModelImpl._tagName;

		expertiseTagModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<ExpertiseTag> toCacheModel() {
		ExpertiseTagCacheModel expertiseTagCacheModel = new ExpertiseTagCacheModel();

		expertiseTagCacheModel.tagId = getTagId();

		expertiseTagCacheModel.groupId = getGroupId();

		expertiseTagCacheModel.companyId = getCompanyId();

		expertiseTagCacheModel.userId = getUserId();

		expertiseTagCacheModel.userName = getUserName();

		String userName = expertiseTagCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			expertiseTagCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			expertiseTagCacheModel.createDate = createDate.getTime();
		}
		else {
			expertiseTagCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			expertiseTagCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			expertiseTagCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		expertiseTagCacheModel.tagName = getTagName();

		String tagName = expertiseTagCacheModel.tagName;

		if ((tagName != null) && (tagName.length() == 0)) {
			expertiseTagCacheModel.tagName = null;
		}

		expertiseTagCacheModel.userCount = getUserCount();

		return expertiseTagCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(19);

		sb.append("{tagId=");
		sb.append(getTagId());
		sb.append(", groupId=");
		sb.append(getGroupId());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", userName=");
		sb.append(getUserName());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append(", tagName=");
		sb.append(getTagName());
		sb.append(", userCount=");
		sb.append(getUserCount());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(31);

		sb.append("<model><model-name>");
		sb.append("com.idetronic.portlet.model.ExpertiseTag");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>tagId</column-name><column-value><![CDATA[");
		sb.append(getTagId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>groupId</column-name><column-value><![CDATA[");
		sb.append(getGroupId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userName</column-name><column-value><![CDATA[");
		sb.append(getUserName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>tagName</column-name><column-value><![CDATA[");
		sb.append(getTagName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userCount</column-name><column-value><![CDATA[");
		sb.append(getUserCount());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = ExpertiseTag.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			ExpertiseTag.class
		};
	private long _tagId;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userUuid;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private String _tagName;
	private String _originalTagName;
	private int _userCount;
	private long _columnBitmask;
	private ExpertiseTag _escapedModel;
}