/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.idetronic.portlet.model.impl;

import com.idetronic.portlet.model.UserEntries_ExpertiseTags;
import com.idetronic.portlet.model.UserEntries_ExpertiseTagsModel;
import com.idetronic.portlet.service.persistence.UserEntries_ExpertiseTagsPK;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.util.PortalUtil;

import java.io.Serializable;

import java.sql.Types;

import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the UserEntries_ExpertiseTags service. Represents a row in the &quot;ide_UserEntries_ExpertiseTags&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.idetronic.portlet.model.UserEntries_ExpertiseTagsModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link UserEntries_ExpertiseTagsImpl}.
 * </p>
 *
 * @author Mazlan Mat
 * @see UserEntries_ExpertiseTagsImpl
 * @see com.idetronic.portlet.model.UserEntries_ExpertiseTags
 * @see com.idetronic.portlet.model.UserEntries_ExpertiseTagsModel
 * @generated
 */
public class UserEntries_ExpertiseTagsModelImpl extends BaseModelImpl<UserEntries_ExpertiseTags>
	implements UserEntries_ExpertiseTagsModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a user entries_ expertise tags model instance should use the {@link com.idetronic.portlet.model.UserEntries_ExpertiseTags} interface instead.
	 */
	public static final String TABLE_NAME = "ide_UserEntries_ExpertiseTags";
	public static final Object[][] TABLE_COLUMNS = {
			{ "userId", Types.BIGINT },
			{ "tagId", Types.BIGINT }
		};
	public static final String TABLE_SQL_CREATE = "create table ide_UserEntries_ExpertiseTags (userId LONG not null,tagId LONG not null,primary key (userId, tagId))";
	public static final String TABLE_SQL_DROP = "drop table ide_UserEntries_ExpertiseTags";
	public static final String ORDER_BY_JPQL = " ORDER BY userEntries_ExpertiseTags.id.userId ASC, userEntries_ExpertiseTags.id.tagId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY ide_UserEntries_ExpertiseTags.userId ASC, ide_UserEntries_ExpertiseTags.tagId ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.idetronic.portlet.model.UserEntries_ExpertiseTags"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.idetronic.portlet.model.UserEntries_ExpertiseTags"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.idetronic.portlet.model.UserEntries_ExpertiseTags"),
			true);
	public static long TAGID_COLUMN_BITMASK = 1L;
	public static long USERID_COLUMN_BITMASK = 2L;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.idetronic.portlet.model.UserEntries_ExpertiseTags"));

	public UserEntries_ExpertiseTagsModelImpl() {
	}

	@Override
	public UserEntries_ExpertiseTagsPK getPrimaryKey() {
		return new UserEntries_ExpertiseTagsPK(_userId, _tagId);
	}

	@Override
	public void setPrimaryKey(UserEntries_ExpertiseTagsPK primaryKey) {
		setUserId(primaryKey.userId);
		setTagId(primaryKey.tagId);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return new UserEntries_ExpertiseTagsPK(_userId, _tagId);
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey((UserEntries_ExpertiseTagsPK)primaryKeyObj);
	}

	@Override
	public Class<?> getModelClass() {
		return UserEntries_ExpertiseTags.class;
	}

	@Override
	public String getModelClassName() {
		return UserEntries_ExpertiseTags.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("userId", getUserId());
		attributes.put("tagId", getTagId());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		Long tagId = (Long)attributes.get("tagId");

		if (tagId != null) {
			setTagId(tagId);
		}
	}

	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_columnBitmask |= USERID_COLUMN_BITMASK;

		if (!_setOriginalUserId) {
			_setOriginalUserId = true;

			_originalUserId = _userId;
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() throws SystemException {
		return PortalUtil.getUserValue(getUserId(), "uuid", _userUuid);
	}

	@Override
	public void setUserUuid(String userUuid) {
		_userUuid = userUuid;
	}

	public long getOriginalUserId() {
		return _originalUserId;
	}

	@Override
	public long getTagId() {
		return _tagId;
	}

	@Override
	public void setTagId(long tagId) {
		_columnBitmask |= TAGID_COLUMN_BITMASK;

		if (!_setOriginalTagId) {
			_setOriginalTagId = true;

			_originalTagId = _tagId;
		}

		_tagId = tagId;
	}

	public long getOriginalTagId() {
		return _originalTagId;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public UserEntries_ExpertiseTags toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (UserEntries_ExpertiseTags)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		UserEntries_ExpertiseTagsImpl userEntries_ExpertiseTagsImpl = new UserEntries_ExpertiseTagsImpl();

		userEntries_ExpertiseTagsImpl.setUserId(getUserId());
		userEntries_ExpertiseTagsImpl.setTagId(getTagId());

		userEntries_ExpertiseTagsImpl.resetOriginalValues();

		return userEntries_ExpertiseTagsImpl;
	}

	@Override
	public int compareTo(UserEntries_ExpertiseTags userEntries_ExpertiseTags) {
		UserEntries_ExpertiseTagsPK primaryKey = userEntries_ExpertiseTags.getPrimaryKey();

		return getPrimaryKey().compareTo(primaryKey);
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof UserEntries_ExpertiseTags)) {
			return false;
		}

		UserEntries_ExpertiseTags userEntries_ExpertiseTags = (UserEntries_ExpertiseTags)obj;

		UserEntries_ExpertiseTagsPK primaryKey = userEntries_ExpertiseTags.getPrimaryKey();

		if (getPrimaryKey().equals(primaryKey)) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey().hashCode();
	}

	@Override
	public void resetOriginalValues() {
		UserEntries_ExpertiseTagsModelImpl userEntries_ExpertiseTagsModelImpl = this;

		userEntries_ExpertiseTagsModelImpl._originalUserId = userEntries_ExpertiseTagsModelImpl._userId;

		userEntries_ExpertiseTagsModelImpl._setOriginalUserId = false;

		userEntries_ExpertiseTagsModelImpl._originalTagId = userEntries_ExpertiseTagsModelImpl._tagId;

		userEntries_ExpertiseTagsModelImpl._setOriginalTagId = false;

		userEntries_ExpertiseTagsModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<UserEntries_ExpertiseTags> toCacheModel() {
		UserEntries_ExpertiseTagsCacheModel userEntries_ExpertiseTagsCacheModel = new UserEntries_ExpertiseTagsCacheModel();

		userEntries_ExpertiseTagsCacheModel.userId = getUserId();

		userEntries_ExpertiseTagsCacheModel.tagId = getTagId();

		return userEntries_ExpertiseTagsCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(5);

		sb.append("{userId=");
		sb.append(getUserId());
		sb.append(", tagId=");
		sb.append(getTagId());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(10);

		sb.append("<model><model-name>");
		sb.append("com.idetronic.portlet.model.UserEntries_ExpertiseTags");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>tagId</column-name><column-value><![CDATA[");
		sb.append(getTagId());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = UserEntries_ExpertiseTags.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			UserEntries_ExpertiseTags.class
		};
	private long _userId;
	private String _userUuid;
	private long _originalUserId;
	private boolean _setOriginalUserId;
	private long _tagId;
	private long _originalTagId;
	private boolean _setOriginalTagId;
	private long _columnBitmask;
	private UserEntries_ExpertiseTags _escapedModel;
}