/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.idetronic.portlet.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.GroupedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the ExpertiseTag service. Represents a row in the &quot;ide_ExpertiseTag&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.idetronic.portlet.model.impl.ExpertiseTagModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.idetronic.portlet.model.impl.ExpertiseTagImpl}.
 * </p>
 *
 * @author Mazlan Mat
 * @see ExpertiseTag
 * @see com.idetronic.portlet.model.impl.ExpertiseTagImpl
 * @see com.idetronic.portlet.model.impl.ExpertiseTagModelImpl
 * @generated
 */
public interface ExpertiseTagModel extends BaseModel<ExpertiseTag>, GroupedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a expertise tag model instance should use the {@link ExpertiseTag} interface instead.
	 */

	/**
	 * Returns the primary key of this expertise tag.
	 *
	 * @return the primary key of this expertise tag
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this expertise tag.
	 *
	 * @param primaryKey the primary key of this expertise tag
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the tag ID of this expertise tag.
	 *
	 * @return the tag ID of this expertise tag
	 */
	public long getTagId();

	/**
	 * Sets the tag ID of this expertise tag.
	 *
	 * @param tagId the tag ID of this expertise tag
	 */
	public void setTagId(long tagId);

	/**
	 * Returns the group ID of this expertise tag.
	 *
	 * @return the group ID of this expertise tag
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this expertise tag.
	 *
	 * @param groupId the group ID of this expertise tag
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this expertise tag.
	 *
	 * @return the company ID of this expertise tag
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this expertise tag.
	 *
	 * @param companyId the company ID of this expertise tag
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this expertise tag.
	 *
	 * @return the user ID of this expertise tag
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this expertise tag.
	 *
	 * @param userId the user ID of this expertise tag
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this expertise tag.
	 *
	 * @return the user uuid of this expertise tag
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this expertise tag.
	 *
	 * @param userUuid the user uuid of this expertise tag
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this expertise tag.
	 *
	 * @return the user name of this expertise tag
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this expertise tag.
	 *
	 * @param userName the user name of this expertise tag
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this expertise tag.
	 *
	 * @return the create date of this expertise tag
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this expertise tag.
	 *
	 * @param createDate the create date of this expertise tag
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this expertise tag.
	 *
	 * @return the modified date of this expertise tag
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this expertise tag.
	 *
	 * @param modifiedDate the modified date of this expertise tag
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the tag name of this expertise tag.
	 *
	 * @return the tag name of this expertise tag
	 */
	@AutoEscape
	public String getTagName();

	/**
	 * Sets the tag name of this expertise tag.
	 *
	 * @param tagName the tag name of this expertise tag
	 */
	public void setTagName(String tagName);

	/**
	 * Returns the user count of this expertise tag.
	 *
	 * @return the user count of this expertise tag
	 */
	public int getUserCount();

	/**
	 * Sets the user count of this expertise tag.
	 *
	 * @param userCount the user count of this expertise tag
	 */
	public void setUserCount(int userCount);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(ExpertiseTag expertiseTag);

	@Override
	public int hashCode();

	@Override
	public CacheModel<ExpertiseTag> toCacheModel();

	@Override
	public ExpertiseTag toEscapedModel();

	@Override
	public ExpertiseTag toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}