/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.idetronic.portlet.model;

import com.idetronic.portlet.service.persistence.UserEntries_ExpertiseTagsPK;

import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the UserEntries_ExpertiseTags service. Represents a row in the &quot;ide_UserEntries_ExpertiseTags&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.idetronic.portlet.model.impl.UserEntries_ExpertiseTagsModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.idetronic.portlet.model.impl.UserEntries_ExpertiseTagsImpl}.
 * </p>
 *
 * @author Mazlan Mat
 * @see UserEntries_ExpertiseTags
 * @see com.idetronic.portlet.model.impl.UserEntries_ExpertiseTagsImpl
 * @see com.idetronic.portlet.model.impl.UserEntries_ExpertiseTagsModelImpl
 * @generated
 */
public interface UserEntries_ExpertiseTagsModel extends BaseModel<UserEntries_ExpertiseTags> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a user entries_ expertise tags model instance should use the {@link UserEntries_ExpertiseTags} interface instead.
	 */

	/**
	 * Returns the primary key of this user entries_ expertise tags.
	 *
	 * @return the primary key of this user entries_ expertise tags
	 */
	public UserEntries_ExpertiseTagsPK getPrimaryKey();

	/**
	 * Sets the primary key of this user entries_ expertise tags.
	 *
	 * @param primaryKey the primary key of this user entries_ expertise tags
	 */
	public void setPrimaryKey(UserEntries_ExpertiseTagsPK primaryKey);

	/**
	 * Returns the user ID of this user entries_ expertise tags.
	 *
	 * @return the user ID of this user entries_ expertise tags
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this user entries_ expertise tags.
	 *
	 * @param userId the user ID of this user entries_ expertise tags
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this user entries_ expertise tags.
	 *
	 * @return the user uuid of this user entries_ expertise tags
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this user entries_ expertise tags.
	 *
	 * @param userUuid the user uuid of this user entries_ expertise tags
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the tag ID of this user entries_ expertise tags.
	 *
	 * @return the tag ID of this user entries_ expertise tags
	 */
	public long getTagId();

	/**
	 * Sets the tag ID of this user entries_ expertise tags.
	 *
	 * @param tagId the tag ID of this user entries_ expertise tags
	 */
	public void setTagId(long tagId);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(UserEntries_ExpertiseTags userEntries_ExpertiseTags);

	@Override
	public int hashCode();

	@Override
	public CacheModel<UserEntries_ExpertiseTags> toCacheModel();

	@Override
	public UserEntries_ExpertiseTags toEscapedModel();

	@Override
	public UserEntries_ExpertiseTags toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}